export const DEPOP_MATERIALS = [
  { id: 'acrylic', label: 'Acrylic' },
  { id: 'alpaca', label: 'Alpaca' },
  { id: 'bamboo', label: 'Bamboo' },
  { id: 'canvas', label: 'Canvas' },
  { id: 'cashmere', label: 'Cashmere' },
  { id: 'chiffon', label: 'Chiffon' },
  { id: 'corduroy', label: 'Corduroy' },
  { id: 'cotton', label: 'Cotton' },
  { id: 'denim', label: 'Denim' },
  { id: 'down', label: 'Down' },
  { id: 'faux_fur', label: 'Faux fur' },
  { id: 'faux_leather', label: 'Faux leather' },
  { id: 'flannel', label: 'Flannel' },
  { id: 'fleece', label: 'Fleece' },
  { id: 'lace', label: 'Lace' },
  { id: 'leather', label: 'Leather' },
  { id: 'linen', label: 'Linen' },
  { id: 'merino', label: 'Merino wool' },
  { id: 'mesh', label: 'Mesh' },
  { id: 'mohair', label: 'Mohair' },
  { id: 'nylon', label: 'Nylon' },
  { id: 'polyester', label: 'Polyester' },
  { id: 'rayon', label: 'Rayon' },
  { id: 'satin', label: 'Satin' },
  { id: 'silk', label: 'Silk' },
  { id: 'suede', label: 'Suede' },
  { id: 'tweed', label: 'Tweed' },
  { id: 'velour', label: 'Velour' },
  { id: 'velvet', label: 'Velvet' },
  { id: 'viscose', label: 'Viscose' },
  { id: 'wool', label: 'Wool' }
];
