export const DEPOP_COUNTRIES = [
  { id: "Afghanistan", label: "Afghanistan", countryCode: "AF" },
  { id: "Algeria", label: "Algeria", countryCode: "DZ" },
  { id: "American Samoa", label: "American Samoa", countryCode: "AS" },
  { id: "Andorra", label: "Andorra", countryCode: "AD" },
  { id: "Angola", label: "Angola", countryCode: "AO" },
  { id: "Anguilla", label: "Anguilla", countryCode: "AI" },
  { id: "Antarctica", label: "Antarctica", countryCode: "AQ" },
  { id: "Antigua & Barbuda", label: "Antigua & Barbuda", countryCode: "AG" },
  { id: "Argentina", label: "Argentina", countryCode: "AR" },
  { id: "Armenia", label: "Armenia", countryCode: "AM" },
  { id: "Aruba", label: "Aruba", countryCode: "AW" },
  { id: "Ascension Island", label: "Ascension Island", countryCode: "AC" },
  { id: "Australia", label: "Australia", countryCode: "AU" },
  { id: "Austria", label: "Austria", countryCode: "AT" },
  { id: "Azerbaijan", label: "Azerbaijan", countryCode: "AZ" },
  { id: "Bahamas", label: "Bahamas", countryCode: "BS" },
  { id: "Bahrain", label: "Bahrain", countryCode: "BH" },
  { id: "Bangladesh", label: "Bangladesh", countryCode: "BD" },
  { id: "Barbados", label: "Barbados", countryCode: "BB" },
  { id: "Belgium", label: "Belgium", countryCode: "BE" },
  { id: "Belize", label: "Belize", countryCode: "BZ" },
  { id: "Benin", label: "Benin", countryCode: "BJ" },
  { id: "Bermuda", label: "Bermuda", countryCode: "BM" },
  { id: "Bhutan", label: "Bhutan", countryCode: "BT" },
  { id: "Bolivia", label: "Bolivia", countryCode: "BO" },
  { id: "Bosnia & Herzegovina", label: "Bosnia & Herzegovina", countryCode: "BA" },
  { id: "Botswana", label: "Botswana", countryCode: "BW" },
  { id: "Bouvet Island", label: "Bouvet Island", countryCode: "BV" },
  { id: "Brazil", label: "Brazil", countryCode: "BR" },
  { id: "British Indian Ocean Territory", label: "British Indian Ocean Territory", countryCode: "IO" },
  { id: "British Virgin Islands", label: "British Virgin Islands", countryCode: "VG" },
  { id: "Brunei", label: "Brunei", countryCode: "BN" },
  { id: "Bulgaria", label: "Bulgaria", countryCode: "BG" },
  { id: "Burkina Faso", label: "Burkina Faso", countryCode: "BF" },
  { id: "Burundi", label: "Burundi", countryCode: "BI" },
  { id: "Cambodia", label: "Cambodia", countryCode: "KH" },
  { id: "Cameroon", label: "Cameroon", countryCode: "CM" },
  { id: "Canada", label: "Canada", countryCode: "CA" },
  { id: "Canary Islands", label: "Canary Islands", countryCode: "IC" },
  { id: "Cape Verde", label: "Cape Verde", countryCode: "CV" },
  { id: "Caribbean Netherlands", label: "Caribbean Netherlands", countryCode: "BQ" },
  { id: "Cayman Islands", label: "Cayman Islands", countryCode: "KY" },
  { id: "Central African Republic", label: "Central African Republic", countryCode: "CF" },
  { id: "Ceuta & Melilla", label: "Ceuta & Melilla", countryCode: "EA" },
  { id: "Chad", label: "Chad", countryCode: "TD" },
  { id: "Chile", label: "Chile", countryCode: "CL" },
  { id: "Christmas Island", label: "Christmas Island", countryCode: "CX" },
  { id: "Clipperton Island", label: "Clipperton Island", countryCode: "CP" },
  { id: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands", countryCode: "CC" },
  { id: "Colombia", label: "Colombia", countryCode: "CO" },
  { id: "Comoros", label: "Comoros", countryCode: "KM" },
  { id: "Cook Islands", label: "Cook Islands", countryCode: "CK" },
  { id: "Costa Rica", label: "Costa Rica", countryCode: "CR" },
  { id: "Croatia", label: "Croatia", countryCode: "HR" },
  { id: "Curaçao", label: "Curaçao", countryCode: "CW" },
  { id: "Cyprus", label: "Cyprus", countryCode: "CY" },
  { id: "Czechia", label: "Czechia", countryCode: "CZ" },
  { id: "Denmark", label: "Denmark", countryCode: "DK" },
  { id: "Diego Garcia", label: "Diego Garcia", countryCode: "DG" },
  { id: "Djibouti", label: "Djibouti", countryCode: "DJ" },
  { id: "Dominica", label: "Dominica", countryCode: "DM" },
  { id: "Dominican Republic", label: "Dominican Republic", countryCode: "DO" },
  { id: "Ecuador", label: "Ecuador", countryCode: "EC" },
  { id: "Egypt", label: "Egypt", countryCode: "EG" },
  { id: "El Salvador", label: "El Salvador", countryCode: "SV" },
  { id: "Equatorial Guinea", label: "Equatorial Guinea", countryCode: "GQ" },
  { id: "Eritrea", label: "Eritrea", countryCode: "ER" },
  { id: "Estonia", label: "Estonia", countryCode: "EE" },
  { id: "Ethiopia", label: "Ethiopia", countryCode: "ET" },
  { id: "Falkland Islands", label: "Falkland Islands", countryCode: "FK" },
  { id: "Faroe Islands", label: "Faroe Islands", countryCode: "FO" },
  { id: "Fiji", label: "Fiji", countryCode: "FJ" },
  { id: "Finland", label: "Finland", countryCode: "FI" },
  { id: "France", label: "France", countryCode: "FR" },
  { id: "French Guiana", label: "French Guiana", countryCode: "GF" },
  { id: "French Polynesia", label: "French Polynesia", countryCode: "PF" },
  { id: "French Southern Territories", label: "French Southern Territories", countryCode: "TF" },
  { id: "Gabon", label: "Gabon", countryCode: "GA" },
  { id: "Gambia", label: "Gambia", countryCode: "GM" },
  { id: "Georgia", label: "Georgia", countryCode: "GE" },
  { id: "Germany", label: "Germany", countryCode: "DE" },
  { id: "Ghana", label: "Ghana", countryCode: "GH" },
  { id: "Gibraltar", label: "Gibraltar", countryCode: "GI" },
  { id: "Greece", label: "Greece", countryCode: "GR" },
  { id: "Greenland", label: "Greenland", countryCode: "GL" },
  { id: "Grenada", label: "Grenada", countryCode: "GD" },
  { id: "Guadeloupe", label: "Guadeloupe", countryCode: "GP" },
  { id: "Guam", label: "Guam", countryCode: "GU" },
  { id: "Guatemala", label: "Guatemala", countryCode: "GT" },
  { id: "Guernsey", label: "Guernsey", countryCode: "GG" },
  { id: "Guinea", label: "Guinea", countryCode: "GN" },
  { id: "GuineaBissau", label: "GuineaBissau", countryCode: "GW" },
  { id: "Guyana", label: "Guyana", countryCode: "GY" },
  { id: "Haiti", label: "Haiti", countryCode: "HT" },
  { id: "Heard & McDonald Islands", label: "Heard & McDonald Islands", countryCode: "HM" },
  { id: "Honduras", label: "Honduras", countryCode: "HN" },
  { id: "Hong Kong (China)", label: "Hong Kong (China)", countryCode: "HK" },
  { id: "Hungary", label: "Hungary", countryCode: "HU" },
  { id: "Iceland", label: "Iceland", countryCode: "IS" },
  { id: "India", label: "India", countryCode: "IN" },
  { id: "Indonesia", label: "Indonesia", countryCode: "ID" },
  { id: "Ireland", label: "Ireland", countryCode: "IE" },
  { id: "Isle of Man", label: "Isle of Man", countryCode: "IM" },
  { id: "Israel", label: "Israel", countryCode: "IL" },
  { id: "Italy", label: "Italy", countryCode: "IT" },
  { id: "Jamaica", label: "Jamaica", countryCode: "JM" },
  { id: "Japan", label: "Japan", countryCode: "JP" },
  { id: "Jersey", label: "Jersey", countryCode: "JE" },
  { id: "Jordan", label: "Jordan", countryCode: "JO" },
  { id: "Kazakhstan", label: "Kazakhstan", countryCode: "KZ" },
  { id: "Kenya", label: "Kenya", countryCode: "KE" },
  { id: "Kiribati", label: "Kiribati", countryCode: "KI" },
  { id: "Kosovo", label: "Kosovo", countryCode: "XK" },
  { id: "Kuwait", label: "Kuwait", countryCode: "KW" },
  { id: "Kyrgyzstan", label: "Kyrgyzstan", countryCode: "KG" },
  { id: "Laos", label: "Laos", countryCode: "LA" },
  { id: "Latvia", label: "Latvia", countryCode: "LV" },
  { id: "Lesotho", label: "Lesotho", countryCode: "LS" },
  { id: "Libya", label: "Libya", countryCode: "LY" },
  { id: "Liechtenstein", label: "Liechtenstein", countryCode: "LI" },
  { id: "Lithuania", label: "Lithuania", countryCode: "LT" },
  { id: "Luxembourg", label: "Luxembourg", countryCode: "LU" },
  { id: "Macau (China)", label: "Macau (China)", countryCode: "MO" },
  { id: "Macedonia", label: "Macedonia", countryCode: "MK" },
  { id: "Madagascar", label: "Madagascar", countryCode: "MG" },
  { id: "Malawi", label: "Malawi", countryCode: "MW" },
  { id: "Malaysia", label: "Malaysia", countryCode: "MY" },
  { id: "Maldives", label: "Maldives", countryCode: "MV" },
  { id: "Mali", label: "Mali", countryCode: "ML" },
  { id: "Malta", label: "Malta", countryCode: "MT" },
  { id: "Marshall Islands", label: "Marshall Islands", countryCode: "MH" },
  { id: "Martinique", label: "Martinique", countryCode: "MQ" },
  { id: "Mauritania", label: "Mauritania", countryCode: "MR" },
  { id: "Mauritius", label: "Mauritius", countryCode: "MU" },
  { id: "Mayotte", label: "Mayotte", countryCode: "YT" },
  { id: "Mexico", label: "Mexico", countryCode: "MX" },
  { id: "Micronesia", label: "Micronesia", countryCode: "FM" },
  { id: "Moldova", label: "Moldova", countryCode: "MD" },
  { id: "Monaco", label: "Monaco", countryCode: "MC" },
  { id: "Mongolia", label: "Mongolia", countryCode: "MN" },
  { id: "Montenegro", label: "Montenegro", countryCode: "ME" },
  { id: "Montserrat", label: "Montserrat", countryCode: "MS" },
  { id: "Morocco", label: "Morocco", countryCode: "MA" },
  { id: "Mozambique", label: "Mozambique", countryCode: "MZ" },
  { id: "Namibia", label: "Namibia", countryCode: "NA" },
  { id: "Nauru", label: "Nauru", countryCode: "NR" },
  { id: "Nepal", label: "Nepal", countryCode: "NP" },
  { id: "Netherlands", label: "Netherlands", countryCode: "NL" },
  { id: "New Caledonia", label: "New Caledonia", countryCode: "NC" },
  { id: "New Zealand", label: "New Zealand", countryCode: "NZ" },
  { id: "Nicaragua", label: "Nicaragua", countryCode: "NI" },
  { id: "Niger", label: "Niger", countryCode: "NE" },
  { id: "Nigeria", label: "Nigeria", countryCode: "NG" },
  { id: "Niue", label: "Niue", countryCode: "NU" },
  { id: "Norfolk Island", label: "Norfolk Island", countryCode: "NF" },
  { id: "Northern Mariana Islands", label: "Northern Mariana Islands", countryCode: "MP" },
  { id: "Norway", label: "Norway", countryCode: "NO" },
  { id: "Oman", label: "Oman", countryCode: "OM" },
  { id: "Pakistan", label: "Pakistan", countryCode: "PK" },
  { id: "Palau", label: "Palau", countryCode: "PW" },
  { id: "Palestinian Territories", label: "Palestinian Territories", countryCode: "PS" },
  { id: "Panama", label: "Panama", countryCode: "PA" },
  { id: "Papua New Guinea", label: "Papua New Guinea", countryCode: "PG" },
  { id: "Paraguay", label: "Paraguay", countryCode: "PY" },
  { id: "Peru", label: "Peru", countryCode: "PE" },
  { id: "Philippines", label: "Philippines", countryCode: "PH" },
  { id: "Pitcairn Islands", label: "Pitcairn Islands", countryCode: "PN" },
  { id: "Poland", label: "Poland", countryCode: "PL" },
  { id: "Portugal", label: "Portugal", countryCode: "PT" },
  { id: "Puerto Rico", label: "Puerto Rico", countryCode: "PR" },
  { id: "Qatar", label: "Qatar", countryCode: "QA" },
  { id: "Romania", label: "Romania", countryCode: "RO" },
  { id: "Rwanda", label: "Rwanda", countryCode: "RW" },
  { id: "Réunion", label: "Réunion", countryCode: "RE" },
  { id: "Samoa", label: "Samoa", countryCode: "WS" },
  { id: "San Marino", label: "San Marino", countryCode: "SM" },
  { id: "Saudi Arabia", label: "Saudi Arabia", countryCode: "SA" },
  { id: "Senegal", label: "Senegal", countryCode: "SN" },
  { id: "Serbia", label: "Serbia", countryCode: "RS" },
  { id: "Seychelles", label: "Seychelles", countryCode: "SC" },
  { id: "Singapore", label: "Singapore", countryCode: "SG" },
  { id: "Sint Maarten", label: "Sint Maarten", countryCode: "SX" },
  { id: "Slovakia", label: "Slovakia", countryCode: "SK" },
  { id: "Slovenia", label: "Slovenia", countryCode: "SI" },
  { id: "So. Georgia & So. Sandwich Isl.", label: "So. Georgia & So. Sandwich Isl.", countryCode: "GS" },
  { id: "Solomon Islands", label: "Solomon Islands", countryCode: "SB" },
  { id: "Somalia", label: "Somalia", countryCode: "SO" },
  { id: "South Africa", label: "South Africa", countryCode: "ZA" },
  { id: "South Korea", label: "South Korea", countryCode: "KR" },
  { id: "South Sudan", label: "South Sudan", countryCode: "SS" },
  { id: "Spain", label: "Spain", countryCode: "ES" },
  { id: "Sri Lanka", label: "Sri Lanka", countryCode: "LK" },
  { id: "St. Barthélemy", label: "St. Barthélemy", countryCode: "BL" },
  { id: "St. Helena", label: "St. Helena", countryCode: "SH" },
  { id: "St. Kitts & Nevis", label: "St. Kitts & Nevis", countryCode: "KN" },
  { id: "St. Lucia", label: "St. Lucia", countryCode: "LC" },
  { id: "St. Martin", label: "St. Martin", countryCode: "MF" },
  { id: "St. Pierre & Miquelon", label: "St. Pierre & Miquelon", countryCode: "PM" },
  { id: "St. Vincent & Grenadines", label: "St. Vincent & Grenadines", countryCode: "VC" },
  { id: "Suriname", label: "Suriname", countryCode: "SR" },
  { id: "Svalbard & Jan Mayen", label: "Svalbard & Jan Mayen", countryCode: "SJ" },
  { id: "Swaziland", label: "Swaziland", countryCode: "SZ" },
  { id: "Sweden", label: "Sweden", countryCode: "SE" },
  { id: "Switzerland", label: "Switzerland", countryCode: "CH" },
  { id: "São Tomé & Príncipe", label: "São Tomé & Príncipe", countryCode: "ST" },
  { id: "Taiwan", label: "Taiwan", countryCode: "TW" },
  { id: "Tajikistan", label: "Tajikistan", countryCode: "TJ" },
  { id: "Tanzania", label: "Tanzania", countryCode: "TZ" },
  { id: "Thailand", label: "Thailand", countryCode: "TH" },
  { id: "TimorLeste", label: "TimorLeste", countryCode: "TL" },
  { id: "Togo", label: "Togo", countryCode: "TG" },
  { id: "Tokelau", label: "Tokelau", countryCode: "TK" },
  { id: "Tonga", label: "Tonga", countryCode: "TO" },
  { id: "Trinidad & Tobago", label: "Trinidad & Tobago", countryCode: "TT" },
  { id: "Tristan da Cunha", label: "Tristan da Cunha", countryCode: "TA" },
  { id: "Tunisia", label: "Tunisia", countryCode: "TN" },
  { id: "Turkey", label: "Turkey", countryCode: "TR" },
  { id: "Turkmenistan", label: "Turkmenistan", countryCode: "TM" },
  { id: "Turks & Caicos Islands", label: "Turks & Caicos Islands", countryCode: "TC" },
  { id: "Tuvalu", label: "Tuvalu", countryCode: "TV" },
  { id: "U.S. Outlying Islands", label: "U.S. Outlying Islands", countryCode: "UM" },
  { id: "U.S. Virgin Islands", label: "U.S. Virgin Islands", countryCode: "VI" },
  { id: "Uganda", label: "Uganda", countryCode: "UG" },
  { id: "United Arab Emirates", label: "United Arab Emirates", countryCode: "AE" },
  { id: "United Kingdom", label: "United Kingdom", countryCode: "GB" },
  { id: "United States", label: "United States", countryCode: "US" },
  { id: "Uruguay", label: "Uruguay", countryCode: "UY" },
  { id: "Uzbekistan", label: "Uzbekistan", countryCode: "UZ" },
  { id: "Vanuatu", label: "Vanuatu", countryCode: "VU" },
  { id: "Vatican City", label: "Vatican City", countryCode: "VA" },
  { id: "Venezuela", label: "Venezuela", countryCode: "VE" },
  { id: "Vietnam", label: "Vietnam", countryCode: "VN" },
  { id: "Wallis & Futuna", label: "Wallis & Futuna", countryCode: "WF" },
  { id: "Western Sahara", label: "Western Sahara", countryCode: "EH" },
  { id: "Yemen", label: "Yemen", countryCode: "YE" },
  { id: "Zambia", label: "Zambia", countryCode: "ZM" },
  { id: "Åland Islands", label: "Åland Islands", countryCode: "AX" }
];
