export const DEPOP_STYLES = [
    { id: "streetwear", label: "Streetwear" },
    { id: "sportswear", label: "Sportswear" },
    { id: "loungewear", label: "Loungewear" },
    { id: "goth", label: "Goth" },
    { id: "retro", label: "Retro" },
    { id: "boho", label: "Boho" },
    { id: "western", label: "Western" },
    { id: "indie", label: "Indie" },
    { id: "skater", label: "Skater" },
    { id: "rave", label: "Rave" },
    { id: "costume", label: "Costume" },
    { id: "cosplay", label: "Cosplay" },
    { id: "grunge", label: "Grunge" },
    { id: "emo", label: "Emo" },
    { id: "minimalist", label: "Minimalist" },
    { id: "preppy", label: "Preppy" },
    { id: "avant_garde", label: "Avant Garde" },
    { id: "punk", label: "Punk" },
    { id: "glam", label: "Glam" },
    { id: "regency", label: "Regency" },
    { id: "casual", label: "Casual" },
    { id: "techwear", label: "Utility" },
    { id: "futuristic", label: "Futuristic" },
    { id: "cottage", label: "Cottage" },
    { id: "fairy", label: "Fairy" },
    { id: "kidcore", label: "Kidcore" },
    { id: "y2_k", label: "Y2K" },
    { id: "biker", label: "Biker" },
    { id: "gorpcore", label: "Gorpcore" },
    { id: "twee", label: "Twee" },
    { id: "coquette", label: "Coquette" },
    { id: "whimsygoth", label: "Whimsygoth" }
];
