export const MERCARI_SIZES = {
  WOMENS_APPAREL: [
    { id: 'XXS', label: 'XXS (00)' },
    { id: 'XS', label: 'XS (0-2)' },
    { id: 'S', label: 'S (4-6)' },
    { id: 'M', label: 'M (8-10)' },
    { id: 'L', label: 'L (12-14)' },
    { id: 'XL', label: 'XL (16-18)' },
    { id: 'XXL', label: 'XXL (20)' },
    { id: '3XL', label: '3XL (22-24)' },
    { id: '4XL', label: '4XL (26+)' },
    { id: 'One Size', label: 'One Size' }
  ],
  WOMENS_SHOES: [
    { id: '5', label: '5' },
    { id: '5.5', label: '5.5' },
    { id: '6', label: '6' },
    { id: '6.5', label: '6.5' },
    { id: '7', label: '7' },
    { id: '7.5', label: '7.5' },
    { id: '8', label: '8' },
    { id: '8.5', label: '8.5' },
    { id: '9', label: '9' },
    { id: '9.5', label: '9.5' },
    { id: '10', label: '10' },
    { id: '10.5', label: '10.5' },
    { id: '11', label: '11' },
    { id: '11.5', label: '11.5' },
    { id: '12', label: '12' }
  ],
  WOMENS_BOTTOMS: [
    { id: '23', label: '23 in. (00)' },
    { id: '24', label: '24 in. (0)' },
    { id: '25', label: '25 in. (0)' },
    { id: '26', label: '26 in. (2)' },
    { id: '27', label: '27 in. (4)' },
    { id: '28', label: '28 in. (6)' },
    { id: '29', label: '29 in. (8)' },
    { id: '30', label: '30 in. (10)' },
    { id: '31', label: '31 in. (12)' },
    { id: '32', label: '32 in. (14)' },
    { id: '33', label: '33 in. (16)' },
    { id: '34', label: '34 in. (18)' }
  ],
  MENS_APPAREL: [
    { id: 'XXS', label: 'XXS' },
    { id: 'XS', label: 'XS' },
    { id: 'S', label: 'S' },
    { id: 'M', label: 'M' },
    { id: 'L', label: 'L' },
    { id: 'XL', label: 'XL' },
    { id: 'XXL', label: 'XXL' },
    { id: '3XL', label: '3XL' },
    { id: '4XL', label: '4XL' },
    { id: 'One Size', label: 'One Size' }
  ],
  MENS_SHOES: [
    { id: '6', label: '6' },
    { id: '6.5', label: '6.5' },
    { id: '7', label: '7' },
    { id: '7.5', label: '7.5' },
    { id: '8', label: '8' },
    { id: '8.5', label: '8.5' },
    { id: '9', label: '9' },
    { id: '9.5', label: '9.5' },
    { id: '10', label: '10' },
    { id: '10.5', label: '10.5' },
    { id: '11', label: '11' },
    { id: '11.5', label: '11.5' },
    { id: '12', label: '12' },
    { id: '13', label: '13' },
    { id: '14', label: '14' },
    { id: '15', label: '15' }
  ],
  MENS_BOTTOMS: [
    { id: '28', label: '28 in.' },
    { id: '29', label: '29 in.' },
    { id: '30', label: '30 in.' },
    { id: '31', label: '31 in.' },
    { id: '32', label: '32 in.' },
    { id: '33', label: '33 in.' },
    { id: '34', label: '34 in.' },
    { id: '35', label: '35 in.' },
    { id: '36', label: '36 in.' },
    { id: '37', label: '37 in.' },
    { id: '38', label: '38 in.' },
    { id: '39', label: '39 in.' },
    { id: '40', label: '40 in.' },
    { id: '41', label: '41 in.' },
    { id: '42', label: '42 in.' }
  ],
  KIDS_APPAREL: [
    { id: 'Newborn', label: 'Newborn' },
    { id: '0-3M', label: '0-3 Months' },
    { id: '3-6M', label: '3-6 Months' },
    { id: '6-9M', label: '6-9 Months' },
    { id: '9-12M', label: '9-12 Months' },
    { id: '12-18M', label: '12-18 Months' },
    { id: '18-24M', label: '18-24 Months' },
    { id: '2T', label: '2T' },
    { id: '3T', label: '3T' },
    { id: '4T', label: '4T' },
    { id: '5T', label: '5' },
    { id: 'Kids S', label: 'S (6-7)' },
    { id: 'Kids M', label: 'M (8)' },
    { id: 'Kids L', label: 'L (10-12)' },
    { id: 'Kids XL', label: 'XL (14-16)' }
  ],
  KIDS_SHOES: [
    { id: '1C', label: '1C' }, { id: '2C', label: '2C' }, { id: '3C', label: '3C' },
    { id: '4C', label: '4C' }, { id: '5C', label: '5C' }, { id: '6C', label: '6C' },
    { id: '7C', label: '7C' }, { id: '8C', label: '8C' }, { id: '9C', label: '9C' },
    { id: '10C', label: '10C' }, { id: '11C', label: '11C' }, { id: '12C', label: '12C' },
    { id: '13C', label: '13C' }, { id: '1Y', label: '1Y' }, { id: '2Y', label: '2Y' },
    { id: '3Y', label: '3Y' }, { id: '4Y', label: '4Y' }, { id: '5Y', label: '5Y' },
    { id: '6Y', label: '6Y' }, { id: '7Y', label: '7Y' }
  ]
};
