const DEPOP_TAXONOMY_BASE = [
  { id: "tshirts", path: "Men > Tops > T-shirts", categoryId: "tops", departmentId: "menswear" },
  { id: "hoodies", path: "Men > Tops > Hoodies", categoryId: "tops", departmentId: "menswear" },
  { id: "sweatshirts", path: "Men > Tops > Sweatshirts", categoryId: "tops", departmentId: "menswear" },
  { id: "jumpers", path: "Men > Tops > Jumpers", categoryId: "tops", departmentId: "menswear" },
  { id: "cardigans", path: "Men > Tops > Cardigans", categoryId: "tops", departmentId: "menswear" },
  { id: "shirts", path: "Men > Tops > Shirts", categoryId: "tops", departmentId: "menswear" },
  { id: "polo-shirts", path: "Men > Tops > Polo shirts", categoryId: "tops", departmentId: "menswear" },
  { id: "blouses", path: "Men > Tops > Blouses", categoryId: "tops", departmentId: "menswear" },
  { id: "crop-top", path: "Men > Tops > Crop tops", categoryId: "tops", departmentId: "menswear" },
  { id: "vests-tanks-camis", path: "Men > Tops > Vests", categoryId: "tops", departmentId: "menswear" },
  { id: "corsets", path: "Men > Tops > Corsets", categoryId: "tops", departmentId: "menswear" },
  { id: "bodysuits", path: "Men > Tops > Bodysuits", categoryId: "tops", departmentId: "menswear" },
  { id: "other-tops", path: "Men > Tops > Other", categoryId: "tops", departmentId: "menswear" },
  { id: "jeans", path: "Men > Bottoms > Jeans", categoryId: "bottoms", departmentId: "menswear" },
  { id: "joggers-tracksuits", path: "Men > Bottoms > Sweatpants", categoryId: "bottoms", departmentId: "menswear" },
  { id: "trousers", path: "Men > Bottoms > Trousers", categoryId: "bottoms", departmentId: "menswear" },
  { id: "shorts", path: "Men > Bottoms > Shorts", categoryId: "bottoms", departmentId: "menswear" },
  { id: "leggings", path: "Men > Bottoms > Leggings", categoryId: "bottoms", departmentId: "menswear" },
  { id: "skirts", path: "Men > Bottoms > Skirts", categoryId: "bottoms", departmentId: "menswear" },
  { id: "other-bottoms", path: "Men > Bottoms > Other", categoryId: "bottoms", departmentId: "menswear" },
  { id: "coats", path: "Men > Coats and jackets > Coats", categoryId: "coats-jackets", departmentId: "menswear" },
  { id: "jackets", path: "Men > Coats and jackets > Jackets", categoryId: "coats-jackets", departmentId: "menswear" },
  { id: "gilets", path: "Men > Coats and jackets > Gilets", categoryId: "coats-jackets", departmentId: "menswear" },
  { id: "other-coats-jackets", path: "Men > Coats and jackets > Other", categoryId: "coats-jackets", departmentId: "menswear" },
  { id: "jumpsuit", path: "Men > Jumpsuits and playsuits > Jumpsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "menswear" },
  { id: "playsuit-romper", path: "Men > Jumpsuits and playsuits > Playsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "menswear" },
  { id: "dungarees-overalls", path: "Men > Jumpsuits and playsuits > Dungarees", categoryId: "jumpsuit-and-playsuit", departmentId: "menswear" },
  { id: "other-jumpsuit-and-playsuit", path: "Men > Jumpsuits and playsuits > Other", categoryId: "jumpsuit-and-playsuit", departmentId: "menswear" },
  { id: "suits", path: "Men > Suits > Suits", categoryId: "suits", departmentId: "menswear" },
  { id: "tailored-jackets", path: "Men > Suits > Tailored jackets", categoryId: "suits", departmentId: "menswear" },
  { id: "tailored-trousers", path: "Men > Suits > Tailored trousers", categoryId: "suits", departmentId: "menswear" },
  { id: "waistcoats-vests", path: "Men > Suits > Waistcoats", categoryId: "suits", departmentId: "menswear" },
  { id: "tuxedos", path: "Men > Suits > Tuxedos", categoryId: "suits", departmentId: "menswear" },
  { id: "other-suits", path: "Men > Suits > Other", categoryId: "suits", departmentId: "menswear" },
  { id: "trainers", path: "Men > Footwear > Trainers", categoryId: "footwear", departmentId: "menswear" },
  { id: "slides", path: "Men > Footwear > Slides", categoryId: "footwear", departmentId: "menswear" },
  { id: "sandals", path: "Men > Footwear > Sandals", categoryId: "footwear", departmentId: "menswear" },
  { id: "flipflops", path: "Men > Footwear > Flip flops", categoryId: "footwear", departmentId: "menswear" },
  { id: "slippers", path: "Men > Footwear > Slippers", categoryId: "footwear", departmentId: "menswear" },
  { id: "brogues", path: "Men > Footwear > Brogues", categoryId: "footwear", departmentId: "menswear" },
  { id: "oxfords", path: "Men > Footwear > Oxfords", categoryId: "footwear", departmentId: "menswear" },
  { id: "loafers", path: "Men > Footwear > Loafers", categoryId: "footwear", departmentId: "menswear" },
  { id: "boots", path: "Men > Footwear > Boots", categoryId: "footwear", departmentId: "menswear" },
  { id: "boat-shoes", path: "Men > Footwear > Boat shoes", categoryId: "footwear", departmentId: "menswear" },
  { id: "espadrilles", path: "Men > Footwear > Espadrilles", categoryId: "footwear", departmentId: "menswear" },
  { id: "ballet-shoes", path: "Men > Footwear > Ballet shoes", categoryId: "footwear", departmentId: "menswear" },
  { id: "clogs", path: "Men > Footwear > Clogs", categoryId: "footwear", departmentId: "menswear" },
  { id: "courts", path: "Men > Footwear > Courts", categoryId: "footwear", departmentId: "menswear" },
  { id: "mules", path: "Men > Footwear > Mules", categoryId: "footwear", departmentId: "menswear" },
  { id: "first-shoes-baby-shoes", path: "Men > Footwear > Baby shoes", categoryId: "footwear", departmentId: "menswear" },
  { id: "other-footwear", path: "Men > Footwear > Other", categoryId: "footwear", departmentId: "menswear" },
  { id: "bag", path: "Men > Accessories > Bags", categoryId: "accessories", departmentId: "menswear" },
  { id: "belt", path: "Men > Accessories > Belts", categoryId: "accessories", departmentId: "menswear" },
  { id: "hat", path: "Men > Accessories > Hats and caps", categoryId: "accessories", departmentId: "menswear" },
  { id: "gloves", path: "Men > Accessories > Gloves", categoryId: "accessories", departmentId: "menswear" },
  { id: "scarf-wraps", path: "Men > Accessories > Scarves and wraps", categoryId: "accessories", departmentId: "menswear" },
  { id: "sunglasses", path: "Men > Accessories > Sunglasses", categoryId: "accessories", departmentId: "menswear" },
  { id: "wallet-purses", path: "Men > Accessories > Wallets and cardholders", categoryId: "accessories", departmentId: "menswear" },
  { id: "jewellery", path: "Men > Accessories > Jewellery", categoryId: "accessories", departmentId: "menswear" },
  { id: "watch", path: "Men > Accessories > Watches", categoryId: "accessories", departmentId: "menswear" },
  { id: "hair-accessories", path: "Men > Accessories > Hair accessories", categoryId: "accessories", departmentId: "menswear" },
  { id: "other-accessories", path: "Men > Accessories > Other", categoryId: "accessories", departmentId: "menswear" },
  { id: "pajamas", path: "Men > Nightwear > Pyjamas", categoryId: "nightwear", departmentId: "menswear" },
  { id: "robes", path: "Men > Nightwear > Robes", categoryId: "nightwear", departmentId: "menswear" },
  { id: "other-nightwear", path: "Men > Nightwear > Other", categoryId: "nightwear", departmentId: "menswear" },
  { id: "bandeaus", path: "Men > Underwear > Bandeaus", categoryId: "underwear", departmentId: "menswear" },
  { id: "bras", path: "Men > Underwear > Bras", categoryId: "underwear", departmentId: "menswear" },
  { id: "panties", path: "Men > Underwear > Panties", categoryId: "underwear", departmentId: "menswear" },
  { id: "shapewear", path: "Men > Underwear > Shapewear", categoryId: "underwear", departmentId: "menswear" },
  { id: "boxers-and-briefs", path: "Men > Underwear > Boxers and briefs", categoryId: "underwear", departmentId: "menswear" },
  { id: "vest-undershirts", path: "Men > Underwear > Vests", categoryId: "underwear", departmentId: "menswear" },
  { id: "socks", path: "Men > Underwear > Socks", categoryId: "underwear", departmentId: "menswear" },
  { id: "hosiery-tights", path: "Men > Underwear > Tights", categoryId: "underwear", departmentId: "menswear" },
  { id: "other-underwear", path: "Men > Underwear > Other", categoryId: "underwear", departmentId: "menswear" },
  { id: "bikinis-and-tankini-sets", path: "Men > Swimwear > Bikini and tankini sets", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "bikini-and-tankini-tops", path: "Men > Swimwear > Bikini and tankini tops", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "bikini-and-tankini-bottoms", path: "Men > Swimwear > Bikini and tankini bottoms", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "swimsuit-one-piece", path: "Men > Swimwear > Swimsuits", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "swim-briefs-shorts", path: "Men > Swimwear > Swim briefs and shorts", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "cover-ups", path: "Men > Swimwear > Cover ups", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "other-swim-beach-wear", path: "Men > Swimwear > Other", categoryId: "swim-beach-wear", departmentId: "menswear" },
  { id: "fancy-dress", path: "Men > Fancy dress > Fancy dress", categoryId: "fancy-dress", departmentId: "menswear" },
  { id: "tshirts", path: "Women > Tops > T-shirts", categoryId: "tops", departmentId: "womenswear" },
  { id: "hoodies", path: "Women > Tops > Hoodies", categoryId: "tops", departmentId: "womenswear" },
  { id: "sweatshirts", path: "Women > Tops > Sweatshirts", categoryId: "tops", departmentId: "womenswear" },
  { id: "jumpers", path: "Women > Tops > Jumpers", categoryId: "tops", departmentId: "womenswear" },
  { id: "cardigans", path: "Women > Tops > Cardigans", categoryId: "tops", departmentId: "womenswear" },
  { id: "shirts", path: "Women > Tops > Shirts", categoryId: "tops", departmentId: "womenswear" },
  { id: "polo-shirts", path: "Women > Tops > Polo shirts", categoryId: "tops", departmentId: "womenswear" },
  { id: "blouses", path: "Women > Tops > Blouses", categoryId: "tops", departmentId: "womenswear" },
  { id: "crop-top", path: "Women > Tops > Crop tops", categoryId: "tops", departmentId: "womenswear" },
  { id: "vests-tanks-camis", path: "Women > Tops > Vests", categoryId: "tops", departmentId: "womenswear" },
  { id: "corsets", path: "Women > Tops > Corsets", categoryId: "tops", departmentId: "womenswear" },
  { id: "bodysuits", path: "Women > Tops > Bodysuits", categoryId: "tops", departmentId: "womenswear" },
  { id: "other-tops", path: "Women > Tops > Other", categoryId: "tops", departmentId: "womenswear" },
  { id: "jeans", path: "Women > Bottoms > Jeans", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "joggers-tracksuits", path: "Women > Bottoms > Sweatpants", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "trousers", path: "Women > Bottoms > Trousers", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "shorts", path: "Women > Bottoms > Shorts", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "leggings", path: "Women > Bottoms > Leggings", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "skirts", path: "Women > Bottoms > Skirts", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "other-bottoms", path: "Women > Bottoms > Other", categoryId: "bottoms", departmentId: "womenswear" },
  { id: "casual-dresses", path: "Women > Dresses > Casual dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "formal-dresses", path: "Women > Dresses > Formal dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "going-out-dresses", path: "Women > Dresses > Going out dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "prom-dresses", path: "Women > Dresses > Prom dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "summer-dresses", path: "Women > Dresses > Summer dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "shift-dresses", path: "Women > Dresses > Shift dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "shirt-dresses", path: "Women > Dresses > Shirt dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "wrap-dresses", path: "Women > Dresses > Wrap dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "babydoll-dresses", path: "Women > Dresses > Babydoll dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "bodycon-dresses", path: "Women > Dresses > Bodycon dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "work-dresses", path: "Women > Dresses > Work dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "wedding-dresses", path: "Women > Dresses > Wedding dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "other-dresses", path: "Women > Dresses > Other", categoryId: "dresses", departmentId: "womenswear" },
  { id: "dresses", path: "Women > Dresses > Dresses", categoryId: "dresses", departmentId: "womenswear" },
  { id: "coats", path: "Women > Coats and jackets > Coats", categoryId: "coats-jackets", departmentId: "womenswear" },
  { id: "jackets", path: "Women > Coats and jackets > Jackets", categoryId: "coats-jackets", departmentId: "womenswear" },
  { id: "gilets", path: "Women > Coats and jackets > Gilets", categoryId: "coats-jackets", departmentId: "womenswear" },
  { id: "other-coats-jackets", path: "Women > Coats and jackets > Other", categoryId: "coats-jackets", departmentId: "womenswear" },
  { id: "jumpsuit", path: "Women > Jumpsuits and playsuits > Jumpsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "womenswear" },
  { id: "playsuit-romper", path: "Women > Jumpsuits and playsuits > Playsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "womenswear" },
  { id: "dungarees-overalls", path: "Women > Jumpsuits and playsuits > Dungarees", categoryId: "jumpsuit-and-playsuit", departmentId: "womenswear" },
  { id: "other-jumpsuit-and-playsuit", path: "Women > Jumpsuits and playsuits > Other", categoryId: "jumpsuit-and-playsuit", departmentId: "womenswear" },
  { id: "suits", path: "Women > Suits > Suits", categoryId: "suits", departmentId: "womenswear" },
  { id: "tailored-jackets", path: "Women > Suits > Tailored jackets", categoryId: "suits", departmentId: "womenswear" },
  { id: "tailored-trousers", path: "Women > Suits > Tailored trousers", categoryId: "suits", departmentId: "womenswear" },
  { id: "waistcoats-vests", path: "Women > Suits > Waistcoats", categoryId: "suits", departmentId: "womenswear" },
  { id: "tuxedos", path: "Women > Suits > Tuxedos", categoryId: "suits", departmentId: "womenswear" },
  { id: "other-suits", path: "Women > Suits > Other", categoryId: "suits", departmentId: "womenswear" },
  { id: "trainers", path: "Women > Footwear > Trainers", categoryId: "footwear", departmentId: "womenswear" },
  { id: "slides", path: "Women > Footwear > Slides", categoryId: "footwear", departmentId: "womenswear" },
  { id: "sandals", path: "Women > Footwear > Sandals", categoryId: "footwear", departmentId: "womenswear" },
  { id: "flipflops", path: "Women > Footwear > Flip flops", categoryId: "footwear", departmentId: "womenswear" },
  { id: "slippers", path: "Women > Footwear > Slippers", categoryId: "footwear", departmentId: "womenswear" },
  { id: "brogues", path: "Women > Footwear > Brogues", categoryId: "footwear", departmentId: "womenswear" },
  { id: "oxfords", path: "Women > Footwear > Oxfords", categoryId: "footwear", departmentId: "womenswear" },
  { id: "loafers", path: "Women > Footwear > Loafers", categoryId: "footwear", departmentId: "womenswear" },
  { id: "boots", path: "Women > Footwear > Boots", categoryId: "footwear", departmentId: "womenswear" },
  { id: "boat-shoes", path: "Women > Footwear > Boat shoes", categoryId: "footwear", departmentId: "womenswear" },
  { id: "espadrilles", path: "Women > Footwear > Espadrilles", categoryId: "footwear", departmentId: "womenswear" },
  { id: "ballet-shoes", path: "Women > Footwear > Ballet shoes", categoryId: "footwear", departmentId: "womenswear" },
  { id: "clogs", path: "Women > Footwear > Clogs", categoryId: "footwear", departmentId: "womenswear" },
  { id: "courts", path: "Women > Footwear > Courts", categoryId: "footwear", departmentId: "womenswear" },
  { id: "mules", path: "Women > Footwear > Mules", categoryId: "footwear", departmentId: "womenswear" },
  { id: "first-shoes-baby-shoes", path: "Women > Footwear > Baby shoes", categoryId: "footwear", departmentId: "womenswear" },
  { id: "other-footwear", path: "Women > Footwear > Other", categoryId: "footwear", departmentId: "womenswear" },
  { id: "bag", path: "Women > Accessories > Bags", categoryId: "accessories", departmentId: "womenswear" },
  { id: "belt", path: "Women > Accessories > Belts", categoryId: "accessories", departmentId: "womenswear" },
  { id: "hat", path: "Women > Accessories > Hats and caps", categoryId: "accessories", departmentId: "womenswear" },
  { id: "gloves", path: "Women > Accessories > Gloves", categoryId: "accessories", departmentId: "womenswear" },
  { id: "scarf-wraps", path: "Women > Accessories > Scarves and wraps", categoryId: "accessories", departmentId: "womenswear" },
  { id: "sunglasses", path: "Women > Accessories > Sunglasses", categoryId: "accessories", departmentId: "womenswear" },
  { id: "wallet-purses", path: "Women > Accessories > Wallets and cardholders", categoryId: "accessories", departmentId: "womenswear" },
  { id: "jewellery", path: "Women > Accessories > Jewellery", categoryId: "accessories", departmentId: "womenswear" },
  { id: "watch", path: "Women > Accessories > Watches", categoryId: "accessories", departmentId: "womenswear" },
  { id: "hair-accessories", path: "Women > Accessories > Hair accessories", categoryId: "accessories", departmentId: "womenswear" },
  { id: "other-accessories", path: "Women > Accessories > Other", categoryId: "accessories", departmentId: "womenswear" },
  { id: "pajamas", path: "Women > Nightwear > Pyjamas", categoryId: "nightwear", departmentId: "womenswear" },
  { id: "robes", path: "Women > Nightwear > Robes", categoryId: "nightwear", departmentId: "womenswear" },
  { id: "other-nightwear", path: "Women > Nightwear > Other", categoryId: "nightwear", departmentId: "womenswear" },
  { id: "bandeaus", path: "Women > Underwear > Bandeaus", categoryId: "underwear", departmentId: "womenswear" },
  { id: "bras", path: "Women > Underwear > Bras", categoryId: "underwear", departmentId: "womenswear" },
  { id: "panties", path: "Women > Underwear > Panties", categoryId: "underwear", departmentId: "womenswear" },
  { id: "shapewear", path: "Women > Underwear > Shapewear", categoryId: "underwear", departmentId: "womenswear" },
  { id: "boxers-and-briefs", path: "Women > Underwear > Boxers and briefs", categoryId: "underwear", departmentId: "womenswear" },
  { id: "vest-undershirts", path: "Women > Underwear > Vests", categoryId: "underwear", departmentId: "womenswear" },
  { id: "socks", path: "Women > Underwear > Socks", categoryId: "underwear", departmentId: "womenswear" },
  { id: "hosiery-tights", path: "Women > Underwear > Tights", categoryId: "underwear", departmentId: "womenswear" },
  { id: "other-underwear", path: "Women > Underwear > Other", categoryId: "underwear", departmentId: "womenswear" },
  { id: "bikinis-and-tankini-sets", path: "Women > Swimwear > Bikini and tankini sets", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "bikini-and-tankini-tops", path: "Women > Swimwear > Bikini and tankini tops", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "bikini-and-tankini-bottoms", path: "Women > Swimwear > Bikini and tankini bottoms", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "swimsuit-one-piece", path: "Women > Swimwear > Swimsuits", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "swim-briefs-shorts", path: "Women > Swimwear > Swim briefs and shorts", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "cover-ups", path: "Women > Swimwear > Cover ups", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "other-swim-beach-wear", path: "Women > Swimwear > Other", categoryId: "swim-beach-wear", departmentId: "womenswear" },
  { id: "fancy-dress", path: "Women > Fancy dress > Fancy dress", categoryId: "fancy-dress", departmentId: "womenswear" },
  { id: "tshirts", path: "Kids > Tops > T-shirts", categoryId: "tops", departmentId: "kidswear" },
  { id: "hoodies", path: "Kids > Tops > Hoodies", categoryId: "tops", departmentId: "kidswear" },
  { id: "sweatshirts", path: "Kids > Tops > Sweatshirts", categoryId: "tops", departmentId: "kidswear" },
  { id: "jumpers", path: "Kids > Tops > Jumpers", categoryId: "tops", departmentId: "kidswear" },
  { id: "cardigans", path: "Kids > Tops > Cardigans", categoryId: "tops", departmentId: "kidswear" },
  { id: "shirts", path: "Kids > Tops > Shirts", categoryId: "tops", departmentId: "kidswear" },
  { id: "polo-shirts", path: "Kids > Tops > Polo shirts", categoryId: "tops", departmentId: "kidswear" },
  { id: "blouses", path: "Kids > Tops > Blouses", categoryId: "tops", departmentId: "kidswear" },
  { id: "crop-top", path: "Kids > Tops > Crop tops", categoryId: "tops", departmentId: "kidswear" },
  { id: "vests-tanks-camis", path: "Kids > Tops > Vests", categoryId: "tops", departmentId: "kidswear" },
  { id: "corsets", path: "Kids > Tops > Corsets", categoryId: "tops", departmentId: "kidswear" },
  { id: "bodysuits", path: "Kids > Tops > Bodysuits", categoryId: "tops", departmentId: "kidswear" },
  { id: "other-tops", path: "Kids > Tops > Other", categoryId: "tops", departmentId: "kidswear" },
  { id: "jeans", path: "Kids > Bottoms > Jeans", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "joggers-tracksuits", path: "Kids > Bottoms > Sweatpants", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "trousers", path: "Kids > Bottoms > Trousers", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "shorts", path: "Kids > Bottoms > Shorts", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "leggings", path: "Kids > Bottoms > Leggings", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "skirts", path: "Kids > Bottoms > Skirts", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "other-bottoms", path: "Kids > Bottoms > Other", categoryId: "bottoms", departmentId: "kidswear" },
  { id: "casual-dresses", path: "Kids > Dresses > Casual dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "formal-dresses", path: "Kids > Dresses > Formal dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "going-out-dresses", path: "Kids > Dresses > Going out dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "prom-dresses", path: "Kids > Dresses > Prom dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "summer-dresses", path: "Kids > Dresses > Summer dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "shift-dresses", path: "Kids > Dresses > Shift dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "shirt-dresses", path: "Kids > Dresses > Shirt dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "wrap-dresses", path: "Kids > Dresses > Wrap dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "babydoll-dresses", path: "Kids > Dresses > Babydoll dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "bodycon-dresses", path: "Kids > Dresses > Bodycon dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "work-dresses", path: "Kids > Dresses > Work dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "wedding-dresses", path: "Kids > Dresses > Wedding dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "other-dresses", path: "Kids > Dresses > Other", categoryId: "dresses", departmentId: "kidswear" },
  { id: "dresses", path: "Kids > Dresses > Dresses", categoryId: "dresses", departmentId: "kidswear" },
  { id: "coats", path: "Kids > Coats and jackets > Coats", categoryId: "coats-jackets", departmentId: "kidswear" },
  { id: "jackets", path: "Kids > Coats and jackets > Jackets", categoryId: "coats-jackets", departmentId: "kidswear" },
  { id: "gilets", path: "Kids > Coats and jackets > Gilets", categoryId: "coats-jackets", departmentId: "kidswear" },
  { id: "other-coats-jackets", path: "Kids > Coats and jackets > Other", categoryId: "coats-jackets", departmentId: "kidswear" },
  { id: "jumpsuit", path: "Kids > Jumpsuits and playsuits > Jumpsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "kidswear" },
  { id: "playsuit-romper", path: "Kids > Jumpsuits and playsuits > Playsuits", categoryId: "jumpsuit-and-playsuit", departmentId: "kidswear" },
  { id: "dungarees-overalls", path: "Kids > Jumpsuits and playsuits > Dungarees", categoryId: "jumpsuit-and-playsuit", departmentId: "kidswear" },
  { id: "other-jumpsuit-and-playsuit", path: "Kids > Jumpsuits and playsuits > Other", categoryId: "jumpsuit-and-playsuit", departmentId: "kidswear" },
  { id: "suits", path: "Kids > Suits > Suits", categoryId: "suits", departmentId: "kidswear" },
  { id: "tailored-jackets", path: "Kids > Suits > Tailored jackets", categoryId: "suits", departmentId: "kidswear" },
  { id: "tailored-trousers", path: "Kids > Suits > Tailored trousers", categoryId: "suits", departmentId: "kidswear" },
  { id: "waistcoats-vests", path: "Kids > Suits > Waistcoats", categoryId: "suits", departmentId: "kidswear" },
  { id: "tuxedos", path: "Kids > Suits > Tuxedos", categoryId: "suits", departmentId: "kidswear" },
  { id: "other-suits", path: "Kids > Suits > Other", categoryId: "suits", departmentId: "kidswear" },
  { id: "trainers", path: "Kids > Footwear > Trainers", categoryId: "footwear", departmentId: "kidswear" },
  { id: "slides", path: "Kids > Footwear > Slides", categoryId: "footwear", departmentId: "kidswear" },
  { id: "sandals", path: "Kids > Footwear > Sandals", categoryId: "footwear", departmentId: "kidswear" },
  { id: "flipflops", path: "Kids > Footwear > Flip flops", categoryId: "footwear", departmentId: "kidswear" },
  { id: "slippers", path: "Kids > Footwear > Slippers", categoryId: "footwear", departmentId: "kidswear" },
  { id: "brogues", path: "Kids > Footwear > Brogues", categoryId: "footwear", departmentId: "kidswear" },
  { id: "oxfords", path: "Kids > Footwear > Oxfords", categoryId: "footwear", departmentId: "kidswear" },
  { id: "loafers", path: "Kids > Footwear > Loafers", categoryId: "footwear", departmentId: "kidswear" },
  { id: "boots", path: "Kids > Footwear > Boots", categoryId: "footwear", departmentId: "kidswear" },
  { id: "boat-shoes", path: "Kids > Footwear > Boat shoes", categoryId: "footwear", departmentId: "kidswear" },
  { id: "espadrilles", path: "Kids > Footwear > Espadrilles", categoryId: "footwear", departmentId: "kidswear" },
  { id: "ballet-shoes", path: "Kids > Footwear > Ballet shoes", categoryId: "footwear", departmentId: "kidswear" },
  { id: "clogs", path: "Kids > Footwear > Clogs", categoryId: "footwear", departmentId: "kidswear" },
  { id: "courts", path: "Kids > Footwear > Courts", categoryId: "footwear", departmentId: "kidswear" },
  { id: "mules", path: "Kids > Footwear > Mules", categoryId: "footwear", departmentId: "kidswear" },
  { id: "first-shoes-baby-shoes", path: "Kids > Footwear > Baby shoes", categoryId: "footwear", departmentId: "kidswear" },
  { id: "other-footwear", path: "Kids > Footwear > Other", categoryId: "footwear", departmentId: "kidswear" },
  { id: "bag", path: "Kids > Accessories > Bags", categoryId: "accessories", departmentId: "kidswear" },
  { id: "belt", path: "Kids > Accessories > Belts", categoryId: "accessories", departmentId: "kidswear" },
  { id: "hat", path: "Kids > Accessories > Hats and caps", categoryId: "accessories", departmentId: "kidswear" },
  { id: "gloves", path: "Kids > Accessories > Gloves", categoryId: "accessories", departmentId: "kidswear" },
  { id: "scarf-wraps", path: "Kids > Accessories > Scarves and wraps", categoryId: "accessories", departmentId: "kidswear" },
  { id: "sunglasses", path: "Kids > Accessories > Sunglasses", categoryId: "accessories", departmentId: "kidswear" },
  { id: "wallet-purses", path: "Kids > Accessories > Wallets and cardholders", categoryId: "accessories", departmentId: "kidswear" },
  { id: "jewellery", path: "Kids > Accessories > Jewellery", categoryId: "accessories", departmentId: "kidswear" },
  { id: "watch", path: "Kids > Accessories > Watches", categoryId: "accessories", departmentId: "kidswear" },
  { id: "hair-accessories", path: "Kids > Accessories > Hair accessories", categoryId: "accessories", departmentId: "kidswear" },
  { id: "other-accessories", path: "Kids > Accessories > Other", categoryId: "accessories", departmentId: "kidswear" },
  { id: "pajamas", path: "Kids > Nightwear > Pyjamas", categoryId: "nightwear", departmentId: "kidswear" },
  { id: "robes", path: "Kids > Nightwear > Robes", categoryId: "nightwear", departmentId: "kidswear" },
  { id: "other-nightwear", path: "Kids > Nightwear > Other", categoryId: "nightwear", departmentId: "kidswear" },
  { id: "bikinis-and-tankini-sets", path: "Kids > Swimwear > Bikini and tankini sets", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "bikini-and-tankini-tops", path: "Kids > Swimwear > Bikini and tankini tops", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "bikini-and-tankini-bottoms", path: "Kids > Swimwear > Bikini and tankini bottoms", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "swimsuit-one-piece", path: "Kids > Swimwear > Swimsuits", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "swim-briefs-shorts", path: "Kids > Swimwear > Swim briefs and shorts", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "cover-ups", path: "Kids > Swimwear > Cover ups", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "other-swim-beach-wear", path: "Kids > Swimwear > Other", categoryId: "swim-beach-wear", departmentId: "kidswear" },
  { id: "fancy-dress", path: "Kids > Fancy dress > Fancy dress", categoryId: "fancy-dress", departmentId: "kidswear" },
  { id: "sleepsuits-babygrows", path: "Kids > Sleepsuits and bodysuits > Sleepsuits and bodysuits", categoryId: "sleepsuits-and-bodysuits", departmentId: "kidswear" },
  { id: "bundles", path: "Kids > Clothing bundles > Clothing bundles", categoryId: "bundles", departmentId: "kidswear" },
  { id: "bath-and-body", path: "Everything else > Beauty > Bath and body", categoryId: "beauty", departmentId: "everything-else" },
  { id: "fragrance", path: "Everything else > Beauty > Fragrance", categoryId: "beauty", departmentId: "everything-else" },
  { id: "hair-products", path: "Everything else > Beauty > Haircare", categoryId: "beauty", departmentId: "everything-else" },
  { id: "makeup", path: "Everything else > Beauty > Makeup", categoryId: "beauty", departmentId: "everything-else" },
  { id: "nails", path: "Everything else > Beauty > Nails", categoryId: "beauty", departmentId: "everything-else" },
  { id: "grooming", path: "Everything else > Beauty > Grooming", categoryId: "beauty", departmentId: "everything-else" },
  { id: "skincare", path: "Everything else > Beauty > Skincare", categoryId: "beauty", departmentId: "everything-else" },
  { id: "tools-and-brushes", path: "Everything else > Beauty > Tools and brushes", categoryId: "beauty", departmentId: "everything-else" },
  { id: "face-masks", path: "Everything else > Face masks and coverings > Face masks and coverings", categoryId: "face-masks", departmentId: "everything-else" },
  { id: "dinnerware", path: "Everything else > Home > Dinnerware", categoryId: "home", departmentId: "everything-else" },
  { id: "furniture", path: "Everything else > Home > Furniture", categoryId: "home", departmentId: "everything-else" },
  { id: "decor-home-accesories", path: "Everything else > Home > Home accessories", categoryId: "home", departmentId: "everything-else" },
  { id: "soft-furnishings-textiles", path: "Everything else > Home > Soft furnishings and textiles", categoryId: "home", departmentId: "everything-else" },
  { id: "storage-and-organisation", path: "Everything else > Home > Storage and organisation", categoryId: "home", departmentId: "everything-else" },
  { id: "laptop-cases-bag", path: "Everything else > Tech accessories > Laptop bags and cases", categoryId: "tech-accessories", departmentId: "everything-else" },
  { id: "phone-cases", path: "Everything else > Tech accessories > Phone cases", categoryId: "tech-accessories", departmentId: "everything-else" },
  { id: "cameras-and-accessories", path: "Everything else > Cameras and film > Cameras and film", categoryId: "film", departmentId: "everything-else" },
  { id: "collectibles", path: "Everything else > Art > Collectibles", categoryId: "art", departmentId: "everything-else" },
  { id: "drawing-and-illustrations", path: "Everything else > Art > Drawings and illustrations", categoryId: "art", departmentId: "everything-else" },
  { id: "mixed-media", path: "Everything else > Art > Mixed media", categoryId: "art", departmentId: "everything-else" },
  { id: "paintings", path: "Everything else > Art > Paintings", categoryId: "art", departmentId: "everything-else" },
  { id: "photography", path: "Everything else > Art > Photography", categoryId: "art", departmentId: "everything-else" },
  { id: "prints", path: "Everything else > Art > Prints", categoryId: "art", departmentId: "everything-else" },
  { id: "sculptures", path: "Everything else > Art > Sculptures", categoryId: "art", departmentId: "everything-else" },
  { id: "stickers", path: "Everything else > Art > Stickers", categoryId: "art", departmentId: "everything-else" },
  { id: "books", path: "Everything else > Books and magazines > Books", categoryId: "books-and-magazine", departmentId: "everything-else" },
  { id: "magazines", path: "Everything else > Books and magazines > Magazines", categoryId: "books-and-magazine", departmentId: "everything-else" },
  { id: "cds-and-vinyl", path: "Everything else > Music > CDs and vinyl", categoryId: "music", departmentId: "everything-else" },
  { id: "musical-instruments-and-dj", path: "Everything else > Music > Musical instruments", categoryId: "music", departmentId: "everything-else" },
  { id: "cake-decor", path: "Everything else > Party supplies > Cake decorating", categoryId: "party-supplies", departmentId: "everything-else" },
  { id: "cards-invitations-gift-wrap", path: "Everything else > Party supplies > Cards, invitations, gift wrap", categoryId: "party-supplies", departmentId: "everything-else" },
  { id: "decorations", path: "Everything else > Party supplies > Decorations", categoryId: "party-supplies", departmentId: "everything-else" },
  { id: "favours", path: "Everything else > Party supplies > Party favours", categoryId: "party-supplies", departmentId: "everything-else" },
  { id: "party-hats", path: "Everything else > Party supplies > Party hats", categoryId: "party-supplies", departmentId: "everything-else" },
  { id: "ball-sports", path: "Everything else > Sports equipment > Ball sports", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "camping-hiking", path: "Everything else > Sports equipment > Camping and hiking", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "cycling", path: "Everything else > Sports equipment > Cycling", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "fitness", path: "Everything else > Sports equipment > Fitness", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "golf", path: "Everything else > Sports equipment > Golf", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "skates-skateboards-scooters", path: "Everything else > Sports equipment > Skates, skateboards and scooters", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "raquet-sports", path: "Everything else > Sports equipment > Racquet sports", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "water-sports", path: "Everything else > Sports equipment > Water sports", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "winter-sports", path: "Everything else > Sports equipment > Winter sports", categoryId: "sports-equipment-accesories", departmentId: "everything-else" },
  { id: "action-figures-playsets", path: "Everything else > Toys > Action figures and playsets", categoryId: "toys", departmentId: "everything-else" },
  { id: "building-sets-blocks", path: "Everything else > Toys > Building sets and blocks", categoryId: "toys", departmentId: "everything-else" },
  { id: "cars-vehicles", path: "Everything else > Toys > Cars and vehicles", categoryId: "toys", departmentId: "everything-else" },
  { id: "dolls-accessories", path: "Everything else > Toys > Dolls and accessories", categoryId: "toys", departmentId: "everything-else" },
  { id: "learning-toys", path: "Everything else > Toys > Learning toys", categoryId: "toys", departmentId: "everything-else" },
  { id: "puzzles-games", path: "Everything else > Toys > Puzzles and games", categoryId: "toys", departmentId: "everything-else" },
  { id: "stuffed-animals", path: "Everything else > Toys > Stuffed animals", categoryId: "toys", departmentId: "everything-else" },
  { id: "trading-cards", path: "Everything else > Toys > Trading cards", categoryId: "toys", departmentId: "everything-else" },
  { id: "umbrella", path: "Everything else > Umbrellas > Umbrellas", categoryId: "umbrella", departmentId: "everything-else" }
];

const DEPOP_CATEGORY_MAPPING = {
  // Tops
  "tshirts": ["occasion", "material", "body-fit", "size-fit"],
  "hoodies": ["occasion", "material", "body-fit", "size-fit"],
  "sweatshirts": ["occasion", "material", "body-fit", "size-fit"],
  "jumpers": ["occasion", "material", "body-fit", "size-fit"],
  "cardigans": ["occasion", "material", "body-fit", "size-fit"],
  "shirts": ["occasion", "material", "body-fit", "size-fit"],
  "polo-shirts": ["occasion", "material", "body-fit", "size-fit"],
  "blouses": ["occasion", "material", "body-fit", "size-fit"],
  "crop-top": ["body-fit", "material", "occasion", "size-fit"],
  "vests-tanks-camis": ["occasion", "material", "body-fit", "size-fit"],
  "corsets": ["occasion", "material", "body-fit"],
  "bodysuits": ["occasion", "material", "body-fit", "size-fit"],
  "other-tops": ["material", "body-fit", "occasion", "size-fit"],

  // Bottoms
  "jeans": ["bottom-fit", "bottom-style", "occasion", "material", "body-fit", "size-fit"],
  "joggers-tracksuits": ["bottom-fit", "bottom-style", "occasion", "material", "body-fit", "size-fit"],
  "trousers": ["bottom-fit", "bottom-style", "occasion", "material", "body-fit", "size-fit"],
  "shorts": ["occasion", "material", "body-fit", "size-fit"],
  "leggings": ["bottom-fit", "bottom-style", "occasion", "material", "body-fit", "size-fit"],
  "skirts": ["dress-length", "occasion", "material", "body-fit", "size-fit"],
  "other-bottoms": ["material", "body-fit", "bottom-fit", "occasion", "bottom-style", "size-fit"],

  // Dresses
  "casual-dresses": ["dress-length", "size-fit"],
  "formal-dresses": ["dress-length", "size-fit"],
  "going-out-dresses": ["dress-length", "size-fit"],
  "prom-dresses": ["dress-length", "size-fit"],
  "summer-dresses": ["dress-length", "size-fit"],
  "shift-dresses": ["dress-length", "size-fit"],
  "shirt-dresses": ["dress-length", "size-fit"],
  "wrap-dresses": ["dress-length", "size-fit"],
  "babydoll-dresses": ["dress-length", "size-fit"],
  "bodycon-dresses": ["dress-length", "size-fit"],
  "work-dresses": ["dress-length", "size-fit"],
  "wedding-dresses": ["dress-length", "size-fit"],
  "other-dresses": ["dress-length", "size-fit"],
  "dresses": ["dress-length", "dress-type", "occasion", "material", "body-fit", "size-fit"],

  // Coats and jackets
  "coats": ["coat-type", "occasion", "material", "body-fit", "size-fit"],
  "jackets": ["jacket-type", "occasion", "material", "body-fit", "size-fit"],
  "gilets": ["occasion", "material", "body-fit", "size-fit"],
  "other-coats-jackets": ["material", "body-fit", "occasion", "size-fit"],

  // Jumpsuits and rompers
  "jumpsuit": ["jumpssuit-type", "occasion", "material", "body-fit", "size-fit"],
  "playsuit-romper": ["occasion", "material", "body-fit", "size-fit"],
  "dungarees-overalls": ["dungarees-type", "occasion", "material", "body-fit", "size-fit"],
  "other-jumpsuit-and-playsuit": ["occasion", "material", "body-fit", "size-fit"],

  // Suits
  "suits": ["occasion", "material", "body-fit", "size-fit"],
  "tailored-jackets": ["occasion", "material", "body-fit", "size-fit"],
  "tailored-trousers": ["occasion", "material", "body-fit", "size-fit"],
  "waistcoats-vests": ["occasion", "material", "body-fit", "size-fit"],
  "tuxedos": ["occasion", "material", "body-fit", "size-fit"],
  "other-suits": ["material", "body-fit", "occasion", "size-fit"],

  // Footwear
  "trainers": ["trainers-type", "occasion", "material", "size-fit"],
  "slides": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "sandals": ["shoe-type", "occasion", "material", "size-fit"],
  "flipflops": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "slippers": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "brogues": ["shoe-type", "occasion", "material", "size-fit"],
  "oxfords": ["shoe-type", "occasion", "material", "size-fit"],
  "loafers": ["shoe-type", "occasion", "material", "size-fit"],
  "boots": ["boot-type", "occasion", "material", "size-fit"],
  "boat-shoes": ["shoe-type", "occasion", "material", "size-fit"],
  "espadrilles": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "ballet-shoes": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "clogs": ["heel-type", "shoe-type", "occasion", "material", "size-fit"],
  "courts": ["material", "heel-type", "shoe-type", "occasion", "size-fit"],
  "mules": ["shoe-type", "occasion", "material", "size-fit"],
  "first-shoes-baby-shoes": ["occasion", "material"],
  "other-footwear": ["occasion", "heel-type", "material", "size-fit"],
  
  // Underwear & Nightwear
  "pajamas": ["occasion", "material", "body-fit", "size-fit"],
  "robes": ["occasion", "material", "body-fit", "size-fit"],
  "other-nightwear": ["occasion", "material", "body-fit", "size-fit"],
  "bandeaus": ["occasion", "material", "body-fit", "size-fit"],
  "bras": ["occasion", "material", "body-fit", "size-fit"],
  "panties": ["occasion", "material", "body-fit", "size-fit"],
  "shapewear": ["occasion", "material", "body-fit", "size-fit"],
  "boxers-and-briefs": ["occasion", "material", "body-fit", "size-fit"],
  "vest-undershirts": ["occasion", "material", "body-fit", "size-fit"],
  "socks": ["occasion", "material", "body-fit", "size-fit"],
  "hosiery-tights": ["occasion", "material", "body-fit", "size-fit"],
  "other-underwear": ["occasion", "material", "body-fit", "size-fit"],

  // Swimwear
  "bikinis-and-tankini-sets": ["occasion", "material", "body-fit", "size-fit"],
  "bikini-and-tankini-tops": ["occasion", "material", "body-fit", "size-fit"],
  "bikini-and-tankini-bottoms": ["occasion", "material", "body-fit", "size-fit"],
  "swimsuit-one-piece": ["occasion", "material", "body-fit", "size-fit"],
  "swim-briefs-shorts": ["occasion", "material", "body-fit", "size-fit"],
  "cover-ups": ["occasion", "material", "body-fit", "size-fit"],
  "other-swim-beach-wear": ["occasion", "material", "body-fit", "size-fit"],

  // Beauty
  "bath-and-body": ["beauty-type"],
  "fragrance": ["beauty-type"],
  "hair-products": ["beauty-type"],
  "makeup": ["beauty-type"],
  "nails": ["beauty-type"],
  "grooming": ["beauty-type"],
  "skincare": ["beauty-type"],
  "tools-and-brushes": ["beauty-type"],

  // Accessories
  "bag": ["material"],
  "belt": ["material"],
  "hat": ["material", "size-fit"],
  "gloves": ["material", "size-fit"],
  "scarf-wraps": ["material"],
  "sunglasses": ["material"],
  "wallet-purses": ["material"],
  "jewellery": ["material"],
  "watch": ["material"],
  "hair-accessories": ["material"],
  "other-accessories": ["material"],

  // Everything Else
  "face-masks": ["material"],
  "dinnerware": ["material"],
  "furniture": ["material"],
  "decor-home-accesories": ["material"],
  "soft-furnishings-textiles": ["material"],
  "storage-and-organisation": ["material"],
  "laptop-cases-bag": ["material"],
  "phone-cases": ["material"],
  "cameras-and-accessories": ["material"],
  "collectibles": ["material"],
  "drawing-and-illustrations": ["material"],
  "mixed-media": ["material"],
  "paintings": ["material"],
  "photography": ["material"],
  "prints": ["material"],
  "sculptures": ["material"],
  "stickers": ["material"],
  "books": ["material"],
  "magazines": ["material"],
  "cds-and-vinyl": ["material"],
  "musical-instruments-and-dj": ["material"],
  "cake-decor": ["material"],
  "cards-invitations-gift-wrap": ["material"],
  "decorations": ["material"],
  "favours": ["material"],
  "party-hats": ["material"],
  "ball-sports": ["material"],
  "camping-hiking": ["material"],
  "cycling": ["material"],
  "fitness": ["material"],
  "golf": ["material"],
  "skates-skateboards-scooters": ["material"],
  "raquet-sports": ["material"],
  "water-sports": ["material"],
  "winter-sports": ["material"],
  "action-figures-playsets": ["material"],
  "building-sets-blocks": ["material"],
  "cars-vehicles": ["material"],
  "dolls-accessories": ["material"],
  "learning-toys": ["material"],
  "puzzles-games": ["material"],
  "stuffed-animals": ["material"],
  "trading-cards": ["material"],
  "umbrella": ["material"]
};

const DEPOP_TAXONOMY = DEPOP_TAXONOMY_BASE.map(cat => ({
  ...cat,
  attribute_ids: DEPOP_CATEGORY_MAPPING[cat.id] || []
}));

module.exports = { DEPOP_TAXONOMY, DEPOP_CATEGORY_MAPPING };
