const DEPOP_TAXONOMY = [
  // --- Womenswear ---
  "Womenswear > Tops > T-shirts",
  "Womenswear > Tops > Blouses & Shirts",
  "Womenswear > Tops > Hoodies & Sweatshirts",
  "Womenswear > Tops > Crop Tops",
  "Womenswear > Tops > Tank Tops & Camis",
  "Womenswear > Tops > Bodysuits",
  "Womenswear > Bottoms > Jeans",
  "Womenswear > Bottoms > Pants & Trousers",
  "Womenswear > Bottoms > Shorts",
  "Womenswear > Bottoms > Leggings",
  "Womenswear > Outerwear > Coats",
  "Womenswear > Outerwear > Jackets",
  "Womenswear > Outerwear > Blazers",
  "Womenswear > Outerwear > Vests",
  "Womenswear > Dresses > Mini Dresses",
  "Womenswear > Dresses > Midi Dresses",
  "Womenswear > Dresses > Maxi Dresses",
  "Womenswear > Skirts > Mini Skirts",
  "Womenswear > Skirts > Midi Skirts",
  "Womenswear > Skirts > Maxi Skirts",
  "Womenswear > Shoes > Sneakers",
  "Womenswear > Shoes > Boots",
  "Womenswear > Shoes > Heels",
  "Womenswear > Shoes > Flats & Loafers",
  "Womenswear > Shoes > Sandals",
  "Womenswear > Shoes > Slippers",
  "Womenswear > Bags > Shoulder Bags",
  "Womenswear > Bags > Handbags & Totes",
  "Womenswear > Bags > Backpacks",
  "Womenswear > Accessories > Jewellery",
  "Womenswear > Accessories > Sunglasses",
  "Womenswear > Accessories > Hats & Beanies",
  "Womenswear > Accessories > Belts",
  "Womenswear > Accessories > Watches",
  "Womenswear > Swimwear > Bikinis",
  "Womenswear > Swimwear > One-pieces",
  "Womenswear > Underwear & Lingerie > Bras & Panties",

  // --- Menswear ---
  "Menswear > Tops > T-shirts",
  "Menswear > Tops > Shirts",
  "Menswear > Tops > Hoodies & Sweatshirts",
  "Menswear > Tops > Polos",
  "Menswear > Tops > Tank Tops",
  "Menswear > Bottoms > Jeans",
  "Menswear > Bottoms > Pants & Trousers",
  "Menswear > Bottoms > Shorts",
  "Menswear > Bottoms > Joggers & Sweatpants",
  "Menswear > Outerwear > Coats",
  "Menswear > Outerwear > Jackets",
  "Menswear > Outerwear > Blazers & Suits",
  "Menswear > Shoes > Sneakers",
  "Menswear > Shoes > Boots",
  "Menswear > Shoes > Dress Shoes",
  "Menswear > Shoes > Sandals & Slides",
  "Menswear > Shoes > Loafers",
  "Menswear > Bags > Backpacks",
  "Menswear > Bags > Duffel Bags",
  "Menswear > Bags > Messenger Bags",
  "Menswear > Accessories > Sunglasses",
  "Menswear > Accessories > Hats & Caps",
  "Menswear > Accessories > Belts",
  "Menswear > Accessories > Watches",
  "Menswear > Accessories > Ties",
  "Menswear > Underwear & Socks > Boxers & Briefs",
  "Menswear > Underwear & Socks > Socks",

  // --- Kidswear ---
  "Kidswear > Clothing > Tops",
  "Kidswear > Clothing > Bottoms",
  "Kidswear > Clothing > Outerwear",
  "Kidswear > Shoes > Sneakers",
  "Kidswear > Shoes > Boots"
];

module.exports = { DEPOP_TAXONOMY };
