const POSHMARK_TAXONOMY = [
  "Women > Bags > Baby Bags",
  "Women > Bags > Backpacks",
  "Women > Bags > Clutches & Wristlets",
  "Women > Bags > Cosmetic Bags & Cases",
  "Women > Bags > Crossbody Bags",
  "Women > Bags > Hobos",
  "Women > Bags > Laptop Bags",
  "Women > Bags > Mini Bags",
  "Women > Bags > Satchels",
  "Women > Bags > Shoulder Bags",
  "Women > Bags > Totes",
  "Women > Bags > Travel Bags",
  "Women > Bags > Wallets",
  "Women > Shoes > Ankle Boots & Booties",
  "Women > Shoes > Athletic Shoes",
  "Women > Shoes > Combat & Moto Boots",
  "Women > Shoes > Espadrilles",
  "Women > Shoes > Flats & Loafers",
  "Women > Shoes > Heeled Boots",
  "Women > Shoes > Heels",
  "Women > Shoes > Lace Up Boots",
  "Women > Shoes > Moccasins",
  "Women > Shoes > Mules & Clogs",
  "Women > Shoes > Over the Knee Boots",
  "Women > Shoes > Platforms",
  "Women > Shoes > Sandals",
  "Women > Shoes > Slippers",
  "Women > Shoes > Sneakers",
  "Women > Shoes > Wedges",
  "Women > Shoes > Winter & Rain Boots",
  "Women > Accessories > Belts",
  "Women > Accessories > Face Masks",
  "Women > Accessories > Glasses",
  "Women > Accessories > Gloves & Mittens",
  "Women > Accessories > Hair Accessories",
  "Women > Accessories > Hats",
  "Women > Accessories > Hosiery & Socks",
  "Women > Accessories > Key & Card Holders",
  "Women > Accessories > Laptop Cases",
  "Women > Accessories > Phone Cases",
  "Women > Accessories > Scarves & Wraps",
  "Women > Accessories > Sunglasses",
  "Women > Accessories > Tablet Cases",
  "Women > Accessories > Umbrellas",
  "Women > Accessories > Watches",
  "Women > Dresses > Asymmetrical",
  "Women > Dresses > Backless",
  "Women > Dresses > High Low",
  "Women > Dresses > Long Sleeve",
  "Women > Dresses > Maxi",
  "Women > Dresses > Midi",
  "Women > Dresses > Mini",
  "Women > Dresses > One Shoulder",
  "Women > Dresses > Prom",
  "Women > Dresses > Strapless",
  "Women > Dresses > Wedding",
  "Women > Intimates & Sleepwear > Bandeaus",
  "Women > Intimates & Sleepwear > Bras",
  "Women > Intimates & Sleepwear > Chemises & Slips",
  "Women > Intimates & Sleepwear > Pajamas",
  "Women > Intimates & Sleepwear > Panties",
  "Women > Intimates & Sleepwear > Robes",
  "Women > Intimates & Sleepwear > Shapewear",
  "Women > Intimates & Sleepwear > Sports Bras",
  "Women > Jackets & Coats > Blazers & Suit Jackets",
  "Women > Jackets & Coats > Bomber Jackets",
  "Women > Jackets & Coats > Capes",
  "Women > Jackets & Coats > Jean Jackets",
  "Women > Jackets & Coats > Leather Jackets",
  "Women > Jackets & Coats > Pea Coats",
  "Women > Jackets & Coats > Puffers",
  "Women > Jackets & Coats > Ski & Snow Jackets",
  "Women > Jackets & Coats > Teddy Jackets",
  "Women > Jackets & Coats > Trench Coats",
  "Women > Jackets & Coats > Utility Jackets",
  "Women > Jackets & Coats > Varsity Jackets",
  "Women > Jackets & Coats > Vests",
  "Women > Jeans > Ankle & Cropped",
  "Women > Jeans > Boot Cut",
  "Women > Jeans > Boyfriend",
  "Women > Jeans > Flare & Wide Leg",
  "Women > Jeans > High Rise",
  "Women > Jeans > Jeggings",
  "Women > Jeans > Overalls",
  "Women > Jeans > Skinny",
  "Women > Jeans > Straight Leg",
  "Women > Pants & Jumpsuits > Ankle & Cropped",
  "Women > Pants & Jumpsuits > Boot Cut & Flare",
  "Women > Pants & Jumpsuits > Capris",
  "Women > Pants & Jumpsuits > Jumpsuits & Rompers",
  "Women > Pants & Jumpsuits > Leggings",
  "Women > Pants & Jumpsuits > Pantsuits",
  "Women > Pants & Jumpsuits > Skinny",
  "Women > Pants & Jumpsuits > Straight Leg",
  "Women > Pants & Jumpsuits > Track Pants & Joggers",
  "Women > Pants & Jumpsuits > Trousers",
  "Women > Pants & Jumpsuits > Wide Leg",
  "Women > Shorts > Athletic Shorts",
  "Women > Shorts > Bermudas",
  "Women > Shorts > Bike Shorts",
  "Women > Shorts > Cargos",
  "Women > Shorts > High Waist",
  "Women > Shorts > Jean Shorts",
  "Women > Shorts > Skorts",
  "Women > Skirts > A-Line or Full",
  "Women > Skirts > Asymmetrical",
  "Women > Skirts > Circle & Skater",
  "Women > Skirts > High Low",
  "Women > Skirts > Maxi",
  "Women > Skirts > Midi",
  "Women > Skirts > Mini",
  "Women > Skirts > Pencil",
  "Women > Skirts > Skirt Sets",
  "Women > Sweaters > Cardigans",
  "Women > Sweaters > Cowl & Turtlenecks",
  "Women > Sweaters > Crew & Scoop Necks",
  "Women > Sweaters > Off-the-Shoulder Sweaters",
  "Women > Sweaters > Shrugs & Ponchos",
  "Women > Sweaters > V-Necks",
  "Women > Swim > Bikinis",
  "Women > Swim > Coverups",
  "Women > Swim > One Pieces",
  "Women > Swim > Sarongs",
  "Women > Tops > Blouses",
  "Women > Tops > Bodysuits",
  "Women > Tops > Button Down Shirts",
  "Women > Tops > Camisoles",
  "Women > Tops > Crop Tops",
  "Women > Tops > Jerseys",
  "Women > Tops > Muscle Tees",
  "Women > Tops > Sweatshirts & Hoodies",
  "Women > Tops > Tank Tops",
  "Women > Tops > Tees - Long Sleeve",
  "Women > Tops > Tees - Short Sleeve",
  "Women > Tops > Tunics",
  "Women > Other",
  "Women > Jewelry > Bracelets",
  "Women > Jewelry > Brooches",
  "Women > Jewelry > Earrings",
  "Women > Jewelry > Necklaces",
  "Women > Jewelry > Rings",
  "Women > Makeup > Blush",
  "Women > Makeup > Bronzer & Contour",
  "Women > Makeup > Brows",
  "Women > Makeup > Brushes & Tools",
  "Women > Makeup > Concealer",
  "Women > Makeup > Eye Primer",
  "Women > Makeup > Eyeliner",
  "Women > Makeup > Eyeshadow",
  "Women > Makeup > Foundation",
  "Women > Makeup > Highlighter",
  "Women > Makeup > Lashes",
  "Women > Makeup > Lip Balm & Gloss",
  "Women > Makeup > Lip Liner",
  "Women > Makeup > Lipstick",
  "Women > Makeup > Mascara",
  "Women > Makeup > Nail Tools",
  "Women > Makeup > Press-On Nails",
  "Women > Makeup > Primer",
  "Women > Makeup > Setting Powder & Spray",
  "Women > Skincare > Acne & Blemish",
  "Women > Skincare > Cleanser & Exfoliant",
  "Women > Skincare > Eye Cream",
  "Women > Skincare > Makeup Remover",
  "Women > Skincare > Mask",
  "Women > Skincare > Moisturizer",
  "Women > Skincare > Peel",
  "Women > Skincare > Serum & Face Oil",
  "Women > Skincare > Suncare",
  "Women > Skincare > Toner",
  "Women > Skincare > Tools",
  "Women > Hair > Color",
  "Women > Hair > Conditioner",
  "Women > Hair > Hairspray",
  "Women > Hair > Heat Protectant",
  "Women > Hair > Shampoo",
  "Women > Hair > Styling",
  "Women > Hair > Tools",
  "Women > Hair > Treatment & Mask",
  "Women > Hair > Wigs & Extensions",
  "Women > Bath & Body > Bath Soak & Bubbles",
  "Women > Bath & Body > Body Wash",
  "Women > Bath & Body > Exfoliant & Scrub",
  "Women > Bath & Body > Hair Removal",
  "Women > Bath & Body > Hand & Foot Care",
  "Women > Bath & Body > Hand Soap",
  "Women > Bath & Body > Moisturizer & Body Oil",
  "Women > Bath & Body > Suncare & Tanning",
  "Women > Bath & Body > Tools",
  "Women > Ao Dais",
  "Women > Cheongsams & Qipaos",
  "Women > Dirndls",
  "Women > Dupattas & Stoles",
  "Women > Hanboks",
  "Women > Harem Pants",
  "Women > Hijabs",
  "Women > Huipils",
  "Women > Kaftans",
  "Women > Kimonos & Yukatas",
  "Women > Kurta Bottoms",
  "Women > Kurtas",
  "Women > Lehengas",
  "Women > Palazzo Pants",
  "Women > Patiala Pants",
  "Women > Salwars",
  "Women > Saree Blouses",
  "Women > Sarees",
  "Women > Treggings",
  "Men > Bags > Backpacks",
  "Men > Bags > Belt Bags",
  "Men > Bags > Briefcases",
  "Men > Bags > Duffel Bags",
  "Men > Bags > Laptop Bags",
  "Men > Bags > Luggage & Travel Bags",
  "Men > Bags > Messenger Bags",
  "Men > Bags > Toiletry Bags",
  "Men > Bags > Wallets",
  "Men > Shoes > Athletic Shoes",
  "Men > Shoes > Boat Shoes",
  "Men > Shoes > Boots",
  "Men > Shoes > Chukka Boots",
  "Men > Shoes > Cowboy & Western Boots",
  "Men > Shoes > Loafers & Slip-Ons",
  "Men > Shoes > Oxfords & Derbys",
  "Men > Shoes > Rain & Snow Boots",
  "Men > Shoes > Sandals & Flip-Flops",
  "Men > Shoes > Sneakers",
  "Men > Accessories > Belts",
  "Men > Accessories > Cuff Links",
  "Men > Accessories > Face Masks",
  "Men > Accessories > Glasses",
  "Men > Accessories > Gloves",
  "Men > Accessories > Hats",
  "Men > Accessories > Jewelry",
  "Men > Accessories > Key & Card Holders",
  "Men > Accessories > Money Clips",
  "Men > Accessories > Phone Cases",
  "Men > Accessories > Pocket Squares",
  "Men > Accessories > Scarves",
  "Men > Accessories > Sunglasses",
  "Men > Accessories > Suspenders",
  "Men > Accessories > Ties",
  "Men > Accessories > Watches",
  "Men > Jackets & Coats > Bomber & Varsity",
  "Men > Jackets & Coats > Lightweight & Shirt Jackets",
  "Men > Jackets & Coats > Military & Field",
  "Men > Jackets & Coats > Pea Coats",
  "Men > Jackets & Coats > Performance Jackets",
  "Men > Jackets & Coats > Puffers",
  "Men > Jackets & Coats > Raincoats",
  "Men > Jackets & Coats > Ski & Snowboard",
  "Men > Jackets & Coats > Trench Coats",
  "Men > Jackets & Coats > Vests",
  "Men > Jackets & Coats > Windbreakers",
  "Men > Jeans > Bootcut",
  "Men > Jeans > Relaxed",
  "Men > Jeans > Skinny",
  "Men > Jeans > Slim",
  "Men > Jeans > Slim Straight",
  "Men > Jeans > Straight",
  "Men > Pants > Cargo",
  "Men > Pants > Chinos & Khakis",
  "Men > Pants > Corduroy",
  "Men > Pants > Dress",
  "Men > Pants > Sweatpants & Joggers",
  "Men > Shirts > Casual Button Down Shirts",
  "Men > Shirts > Dress Shirts",
  "Men > Shirts > Jerseys",
  "Men > Shirts > Polos",
  "Men > Shirts > Sweatshirts & Hoodies",
  "Men > Shirts > Tank Tops",
  "Men > Shirts > Tees - Long Sleeve",
  "Men > Shirts > Tees - Short Sleeve",
  "Men > Shorts > Athletic",
  "Men > Shorts > Cargo",
  "Men > Shorts > Flat Front",
  "Men > Shorts > Hybrids",
  "Men > Shorts > Jean Shorts",
  "Men > Suits & Blazers > Sport Coats & Blazers",
  "Men > Suits & Blazers > Suits",
  "Men > Suits & Blazers > Tuxedos",
  "Men > Suits & Blazers > Vests",
  "Men > Sweaters > Cardigan",
  "Men > Sweaters > Crewneck",
  "Men > Sweaters > Turtleneck",
  "Men > Sweaters > V-Neck",
  "Men > Sweaters > Zip Up",
  "Men > Swim > Board Shorts",
  "Men > Swim > Hybrids",
  "Men > Swim > Rash Guards",
  "Men > Swim > Swim Trunks",
  "Men > Underwear & Socks > Athletic Socks",
  "Men > Underwear & Socks > Boxer Briefs",
  "Men > Underwear & Socks > Boxers",
  "Men > Underwear & Socks > Briefs",
  "Men > Underwear & Socks > Casual Socks",
  "Men > Underwear & Socks > Dress Socks",
  "Men > Underwear & Socks > Undershirts",
  "Men > Other",
  "Men > Grooming > Cleanser",
  "Men > Grooming > Grooming Tools",
  "Men > Grooming > Hair Care",
  "Men > Grooming > Moisturizer",
  "Men > Grooming > Shaving",
  "Men > Grooming > Suncare",
  "Men > Grooming > Treatments",
  "Men > Agbadas & Dashikis",
  "Men > Ao Dais",
  "Men > Changshans",
  "Men > Hanboks",
  "Men > Kaftans",
  "Men > Keffiyehs",
  "Men > Kilts",
  "Men > Kimonos & Yukatas",
  "Men > Kurta Bottoms",
  "Men > Kurtas",
  "Men > Lederhosen",
  "Men > Nehru Jackets",
  "Men > Ponchos & Serapes",
  "Men > Sherwanis",
  "Kids > Shoes > Baby & Walker",
  "Kids > Shoes > Boots",
  "Kids > Shoes > Dress Shoes",
  "Kids > Shoes > Moccasins",
  "Kids > Shoes > Rain & Snow Boots",
  "Kids > Shoes > Sandals & Flip Flops",
  "Kids > Shoes > Slippers",
  "Kids > Shoes > Sneakers",
  "Kids > Shoes > Water Shoes",
  "Kids > Accessories > Bags",
  "Kids > Accessories > Belts",
  "Kids > Accessories > Bibs",
  "Kids > Accessories > Diaper Covers",
  "Kids > Accessories > Face Masks",
  "Kids > Accessories > Hair Accessories",
  "Kids > Accessories > Hats",
  "Kids > Accessories > Jewelry",
  "Kids > Accessories > Mittens",
  "Kids > Accessories > Socks & Tights",
  "Kids > Accessories > Sunglasses",
  "Kids > Accessories > Suspenders",
  "Kids > Accessories > Ties",
  "Kids > Accessories > Underwear",
  "Kids > Accessories > Watches",
  "Kids > Bottoms > Casual",
  "Kids > Bottoms > Formal",
  "Kids > Bottoms > Jeans",
  "Kids > Bottoms > Jumpsuits & Rompers",
  "Kids > Bottoms > Leggings",
  "Kids > Bottoms > Overalls",
  "Kids > Bottoms > Shorts",
  "Kids > Bottoms > Skirts",
  "Kids > Bottoms > Skorts",
  "Kids > Bottoms > Sweatpants & Joggers",
  "Kids > Dresses > Casual",
  "Kids > Dresses > Formal",
  "Kids > Jackets & Coats > Blazers",
  "Kids > Jackets & Coats > Capes",
  "Kids > Jackets & Coats > Jean Jackets",
  "Kids > Jackets & Coats > Pea Coats",
  "Kids > Jackets & Coats > Puffers",
  "Kids > Jackets & Coats > Raincoats",
  "Kids > Jackets & Coats > Vests",
  "Kids > Matching Sets",
  "Kids > One Pieces > Bodysuits",
  "Kids > One Pieces > Footies",
  "Kids > Pajamas > Nightgowns",
  "Kids > Pajamas > Pajama Bottoms",
  "Kids > Pajamas > Pajama Sets",
  "Kids > Pajamas > Pajama Tops",
  "Kids > Pajamas > Robes",
  "Kids > Pajamas > Sleep Sacks",
  "Kids > Shirts & Tops > Blouses",
  "Kids > Shirts & Tops > Button Down Shirts",
  "Kids > Shirts & Tops > Camisoles",
  "Kids > Shirts & Tops > Jerseys",
  "Kids > Shirts & Tops > Polos",
  "Kids > Shirts & Tops > Sweaters",
  "Kids > Shirts & Tops > Sweatshirts & Hoodies",
  "Kids > Shirts & Tops > Tank Tops",
  "Kids > Shirts & Tops > Tees - Long Sleeve",
  "Kids > Shirts & Tops > Tees - Short Sleeve",
  "Kids > Swim > Bikinis",
  "Kids > Swim > Coverups",
  "Kids > Swim > One Piece",
  "Kids > Swim > Rashguards",
  "Kids > Swim > Swim Trunks",
  "Kids > Other",
  "Kids > Bath, Skin & Hair > Bath & Body",
  "Kids > Bath, Skin & Hair > Hair Care",
  "Kids > Bath, Skin & Hair > Moisturizer",
  "Kids > Bath, Skin & Hair > Suncare",
  "Kids > Bath, Skin & Hair > Tools",
  "Kids > Toys > Action Figures & Playsets",
  "Kids > Toys > Building Sets & Blocks",
  "Kids > Toys > Cars & Vehicles",
  "Kids > Toys > Dolls & Accessories",
  "Kids > Toys > Learning Toys",
  "Kids > Toys > Puzzles & Games",
  "Kids > Toys > Stuffed Animals",
  "Kids > Toys > Trading Cards",
  "Kids > Costumes > Dance",
  "Kids > Costumes > Halloween",
  "Kids > Costumes > Seasonal",
  "Kids > Costumes > Superhero",
  "Kids > Costumes > Theater",
  "Home > Accents > Accent Pillows",
  "Home > Accents > Baskets & Bins",
  "Home > Accents > Candles & Holders",
  "Home > Accents > Coffee Table Books",
  "Home > Accents > Curtains & Drapes",
  "Home > Accents > Decor",
  "Home > Accents > Door Mats",
  "Home > Accents > Faux Florals",
  "Home > Accents > Furniture Covers",
  "Home > Accents > Lanterns",
  "Home > Accents > Picture Frames",
  "Home > Accents > Vases",
  "Home > Art > Ceramics",
  "Home > Art > Drawing & Illustrations",
  "Home > Art > Fiber Arts",
  "Home > Art > Glass Art",
  "Home > Art > Mixed Media",
  "Home > Art > Painting",
  "Home > Art > Photography",
  "Home > Art > Posters",
  "Home > Art > Prints",
  "Home > Art > Sculpture",
  "Home > Bath > Bath Accessories",
  "Home > Bath > Bath Storage",
  "Home > Bath > Bath Towels",
  "Home > Bath > Beach Towels",
  "Home > Bath > Hand Towels",
  "Home > Bath > Mats",
  "Home > Bath > Shower Curtains",
  "Home > Bath > Vanity Mirrors",
  "Home > Bath > Vanity Trays",
  "Home > Bath > Wash Cloths",
  "Home > Bedding > Blankets & Throws",
  "Home > Bedding > Comforters",
  "Home > Bedding > Duvet Covers",
  "Home > Bedding > Mattress Covers",
  "Home > Bedding > Pillows",
  "Home > Bedding > Quilts",
  "Home > Bedding > Sheets",
  "Home > Design > Birthday Cards",
  "Home > Design > Business Cards",
  "Home > Design > Planners",
  "Home > Design > Stamps",
  "Home > Design > Stickers",
  "Home > Design > Thank You Cards",
  "Home > Dining > Bar Accessories",
  "Home > Dining > Dinnerware",
  "Home > Dining > Drinkware",
  "Home > Dining > Flatware",
  "Home > Dining > Mugs",
  "Home > Dining > Serveware",
  "Home > Dining > Serving Utensils",
  "Home > Dining > Table Linens",
  "Home > Dining > Water Bottles & Thermoses",
  "Home > Games > Board Games",
  "Home > Games > Card Games",
  "Home > Games > Outdoor Games",
  "Home > Games > Puzzles",
  "Home > Holiday > Garland",
  "Home > Holiday > Holiday Blankets & Throws",
  "Home > Holiday > Holiday Decor",
  "Home > Holiday > Holiday Pillows",
  "Home > Holiday > Ornaments",
  "Home > Holiday > String Lights",
  "Home > Holiday > Wreaths",
  "Home > Kitchen > BBQ & Grilling Tools",
  "Home > Kitchen > Bakeware",
  "Home > Kitchen > Coffee & Tea Accessories",
  "Home > Kitchen > Cookbooks",
  "Home > Kitchen > Cooking Utensils",
  "Home > Kitchen > Cookware",
  "Home > Kitchen > Food Storage",
  "Home > Kitchen > Kitchen Linens",
  "Home > Kitchen > Kitchen Tools",
  "Home > Kitchen > Knives & Cutlery",
  "Home > Office > Arts & Crafts",
  "Home > Office > Binders & Folders",
  "Home > Office > Calendars",
  "Home > Office > Labels & Label Makers",
  "Home > Office > Notebooks & Journals",
  "Home > Office > Pencil Cases",
  "Home > Office > Planners",
  "Home > Office > Shipping Supplies",
  "Home > Office > Stationery",
  "Home > Party Supplies > Cake Candles",
  "Home > Party Supplies > Cake Toppers",
  "Home > Party Supplies > Cards & Invitations",
  "Home > Party Supplies > Decorations",
  "Home > Party Supplies > Disposable Tableware",
  "Home > Party Supplies > Favors",
  "Home > Party Supplies > Gift Wrap",
  "Home > Party Supplies > Hats",
  "Home > Party Supplies > Party Lights",
  "Home > Storage & Organization > Closet Accessories",
  "Home > Storage & Organization > Drawer Liners",
  "Home > Storage & Organization > Garment Bags",
  "Home > Storage & Organization > Jewelry Organizers",
  "Home > Storage & Organization > Makeup Organizers",
  "Home > Storage & Organization > Storage",
  "Home > Wall Decor > Art & Decals",
  "Home > Wall Decor > Clocks",
  "Home > Wall Decor > Display Shelves",
  "Home > Wall Decor > Hooks",
  "Home > Wall Decor > Mirrors",
  "Home > Wall Decor > Tapestries",
  "Home > Wall Decor > Wallpaper",
  "Home > Other",
  "Pets > Dog > Bedding & Blankets",
  "Pets > Dog > Bowls & Feeders",
  "Pets > Dog > Carriers & Travel",
  "Pets > Dog > Clothing & Accessories",
  "Pets > Dog > Collars, Leashes & Harnesses",
  "Pets > Dog > Grooming",
  "Pets > Dog > Housebreaking",
  "Pets > Dog > Toys",
  "Pets > Cat > Beds",
  "Pets > Cat > Bowls & Feeders",
  "Pets > Cat > Carriers & Travel",
  "Pets > Cat > Clothing & Accessories",
  "Pets > Cat > Collars, Leashes  & Harnesses",
  "Pets > Cat > Grooming",
  "Pets > Cat > Scratchers",
  "Pets > Cat > Toys",
  "Pets > Bird > Cages & Covers",
  "Pets > Bird > Feeders & Waterers",
  "Pets > Bird > Perches & Swings",
  "Pets > Bird > Toys",
  "Pets > Fish > Aquarium Kits",
  "Pets > Fish > Cleaning & Maintenance",
  "Pets > Fish > Decor & Accessories",
  "Pets > Reptile > Cleaning & Maintenance",
  "Pets > Reptile > Habitats",
  "Pets > Reptile > Habitat Accessories",
  "Pets > Reptile > Heating & Lights",
  "Pets > Small Pets > Bedding",
  "Pets > Small Pets > Bowls & Feeders",
  "Pets > Small Pets > Cages & Habitats",
  "Pets > Small Pets > Carriers",
  "Pets > Small Pets > Grooming",
  "Pets > Small Pets > Habitat Accessories",
  "Pets > Small Pets > Toys",
  "Pets > Other",
  "Electronics > Cameras, Photo & Video > Digital Cameras",
  "Electronics > Cameras, Photo & Video > Bags & Cases",
  "Electronics > Cameras, Photo & Video > Binoculars & Scopes",
  "Electronics > Cameras, Photo & Video > Film Photography",
  "Electronics > Cameras, Photo & Video > Flashes",
  "Electronics > Cameras, Photo & Video > Lenses",
  "Electronics > Cameras, Photo & Video > Memory Cards",
  "Electronics > Cameras, Photo & Video > Simulated Cameras",
  "Electronics > Cameras, Photo & Video > Tripods & Monopods",
  "Electronics > Cameras, Photo & Video > Underwater Photography",
  "Electronics > Cameras, Photo & Video > Video",
  "Electronics > Cameras, Photo & Video > Camera Straps",
  "Electronics > Computers, Laptops & Parts > Laptops",
  "Electronics > Computers, Laptops & Parts > Cables & Interconnects",
  "Electronics > Computers, Laptops & Parts > Camera Privacy Covers",
  "Electronics > Computers, Laptops & Parts > Computer Cable Adapters",
  "Electronics > Computers, Laptops & Parts > Computer Headsets",
  "Electronics > Computers, Laptops & Parts > Computer Microphones",
  "Electronics > Computers, Laptops & Parts > External Components",
  "Electronics > Computers, Laptops & Parts > Graphics Cards",
  "Electronics > Computers, Laptops & Parts > Internal Components",
  "Electronics > Computers, Laptops & Parts > Keyboards",
  "Electronics > Computers, Laptops & Parts > Memory Card Readers",
  "Electronics > Computers, Laptops & Parts > Mice",
  "Electronics > Computers, Laptops & Parts > Mounts & Stands",
  "Electronics > Computers, Laptops & Parts > Surge Protectors",
  "Electronics > Computers, Laptops & Parts > Single Board Computers",
  "Electronics > Computers, Laptops & Parts > USB Hubs",
  "Electronics > Computers, Laptops & Parts > Webcams",
  "Electronics > Tablets & Accessories > Tablets",
  "Electronics > Tablets & Accessories > eBook Readers",
  "Electronics > Tablets & Accessories > Cases",
  "Electronics > Tablets & Accessories > Chargers",
  "Electronics > Tablets & Accessories > Covers",
  "Electronics > Tablets & Accessories > Power Adapters",
  "Electronics > Tablets & Accessories > Power Cables",
  "Electronics > Tablets & Accessories > Reading Lights",
  "Electronics > Tablets & Accessories > Screen Protectors",
  "Electronics > Tablets & Accessories > Skins",
  "Electronics > Tablets & Accessories > Sleeves",
  "Electronics > Tablets & Accessories > Stands",
  "Electronics > Tablets & Accessories > Tablet Keyboards",
  "Electronics > Cell Phones & Accessories > Cell Phones",
  "Electronics > Cell Phones & Accessories > Holsters & Clips",
  "Electronics > Cell Phones & Accessories > Headsets",
  "Electronics > Cell Phones & Accessories > Screen Protectors",
  "Electronics > Cell Phones & Accessories > Cases",
  "Electronics > Cell Phones & Accessories > Covers",
  "Electronics > Cell Phones & Accessories > Skins & Bumpers",
  "Electronics > Cell Phones & Accessories > Chargers",
  "Electronics > Cell Phones & Accessories > Adapters",
  "Electronics > Cell Phones & Accessories > Cables",
  "Electronics > Video Games & Consoles > Consoles",
  "Electronics > Video Games & Consoles > Handheld Consoles",
  "Electronics > Video Games & Consoles > Batteries & Chargers",
  "Electronics > Video Games & Consoles > Cables",
  "Electronics > Video Games & Consoles > Controllers",
  "Electronics > Video Games & Consoles > Headsets",
  "Electronics > Video Games & Consoles > Gaming Guides",
  "Electronics > Video Games & Consoles > Keyboards",
  "Electronics > Video Games & Consoles > Digital Games",
  "Electronics > Video Games & Consoles > PC Games",
  "Electronics > Video Games & Consoles > Video Games",
  "Electronics > Car Audio, Video & GPS > GPS & Navigation",
  "Electronics > Car Audio, Video & GPS > Amplifiers",
  "Electronics > Car Audio, Video & GPS > Car Stereo Receivers",
  "Electronics > Car Audio, Video & GPS > Changers",
  "Electronics > Car Audio, Video & GPS > Digital Media Receivers",
  "Electronics > Car Audio, Video & GPS > Equalizers",
  "Electronics > Car Audio, Video & GPS > Satellite Radio",
  "Electronics > Car Audio, Video & GPS > Car Headphones",
  "Electronics > Car Audio, Video & GPS > In-Mirror Video",
  "Electronics > Car Audio, Video & GPS > In-Visor Video",
  "Electronics > Car Audio, Video & GPS > On-Dash Cameras",
  "Electronics > Car Audio, Video & GPS > Overhead Video",
  "Electronics > Car Audio, Video & GPS > Surround Processors",
  "Electronics > Car Audio, Video & GPS > TV Tuners",
  "Electronics > Car Audio, Video & GPS > Vehicle Backup Cameras",
  "Electronics > Media > Blank Media",
  "Electronics > Media > CDs",
  "Electronics > Media > DVDs & Blu-ray Discs",
  "Electronics > Media > Media Streamers",
  "Electronics > Media > Media Cases & Organization",
  "Electronics > Media > Vinyl Records",
  "Electronics > Wearables > Smartwatches",
  "Electronics > Wearables > Body Mounted Cameras",
  "Electronics > Wearables > Clips, Arm & Wristbands",
  "Electronics > Wearables > Glasses",
  "Electronics > Wearables > Rings",
  "Electronics > Wearables > Smartwatch Cases",
  "Electronics > Wearables > Wearables Chargers",
  "Electronics > Headphones > Earbud Headphones",
  "Electronics > Headphones > On-Ear Headphones",
  "Electronics > Headphones > Over-Ear Headphones",
  "Electronics > Portable Audio & Video > Boomboxes",
  "Electronics > Portable Audio & Video > CB & Two-Way Radios",
  "Electronics > Portable Audio & Video > Cassette Players",
  "Electronics > Portable Audio & Video > Digital Voice Recorders",
  "Electronics > Portable Audio & Video > MP3 & MP4 Players",
  "Electronics > Portable Audio & Video > Microcassette Recorders",
  "Electronics > Portable Audio & Video > Minidisc Players",
  "Electronics > Portable Audio & Video > Portable & Handheld TVs",
  "Electronics > Portable Audio & Video > Portable CD Players",
  "Electronics > Portable Audio & Video > Portable DVD Players",
  "Electronics > Portable Audio & Video > Portable Speakers",
  "Electronics > Portable Audio & Video > Radios",
  "Electronics > VR, AR & Accessories > PC & Console VR Headsets",
  "Electronics > VR, AR & Accessories > Smartphone VR Headsets",
  "Electronics > VR, AR & Accessories > Standalone VR Headsets",
  "Electronics > VR, AR & Accessories > Cases, Covers & Skins",
  "Electronics > VR, AR & Accessories > Controllers & Sensors",
  "Electronics > VR, AR & Accessories > Parts",
  "Electronics > Networking > Boosters & Antennas",
  "Electronics > Networking > Mobile Broadband Devices",
  "Electronics > Networking > Modems",
  "Electronics > Networking > Modem-Router Combos",
  "Electronics > Networking > Powerline Networking",
  "Electronics > Networking > USB Bluetooth Adapters",
  "Electronics > Networking > USB Wi-Fi Adapters",
  "Electronics > Networking > VoIP Home Phones",
  "Electronics > Networking > VoIP Phone Adapters",
  "Electronics > Networking > Wired Routers",
  "Electronics > Networking > Wireless Access Points",
  "Electronics > Networking > Wireless Routers",
  "Electronics > Other"
];

module.exports = { POSHMARK_TAXONOMY };
