const POSHMARK_TAXONOMY = [
  // --- Women ---
  "Women > Tops > Blouses",
  "Women > Tops > Button Downs",
  "Women > Tops > Camisoles",
  "Women > Tops > Crop Tops",
  "Women > Tops > Polos",
  "Women > Tops > Sweatshirts & Hoodies",
  "Women > Tops > Tank Tops",
  "Women > Tops > Tees - Short Sleeve",
  "Women > Tops > Tees - Long Sleeve",
  "Women > Tops > Tunics",
  "Women > Tops > Other",
  "Women > Jackets & Coats > Blazers",
  "Women > Jackets & Coats > Fur Coats",
  "Women > Jackets & Coats > Jean Jackets",
  "Women > Jackets & Coats > Puffer Jackets",
  "Women > Jackets & Coats > Raincoats",
  "Women > Jackets & Coats > Trench Coats",
  "Women > Jackets & Coats > Vests",
  "Women > Jackets & Coats > Windbreakers",
  "Women > Jackets & Coats > Other",
  "Women > Jeans > Boot Cut",
  "Women > Jeans > Boyfriend",
  "Women > Jeans > Flare & Wide Leg",
  "Women > Jeans > Skinny",
  "Women > Jeans > Straight Leg",
  "Women > Jeans > Other",
  "Women > Pants > Ankle & Cropped",
  "Women > Pants > Cargo",
  "Women > Pants > Khakis & Chinos",
  "Women > Pants > Leggings",
  "Women > Pants > Skinny",
  "Women > Pants > Straight Leg",
  "Women > Pants > Wide Leg",
  "Women > Pants > Other",
  "Women > Shoes > Boots",
  "Women > Shoes > Clogs",
  "Women > Shoes > Flats",
  "Women > Shoes > Heels",
  "Women > Shoes > Mules",
  "Women > Shoes > Sandals",
  "Women > Shoes > Sneakers",
  "Women > Shoes > Wedges",
  "Women > Shoes > Other",
  "Women > Shorts > Bermuda",
  "Women > Shorts > Jean Shorts",
  "Women > Shorts > Khaki Shorts",
  "Women > Shorts > Mini Shorts",
  "Women > Shorts > Other",
  "Women > Sweaters > Cardigans",
  "Women > Sweaters > Crewnecks",
  "Women > Sweaters > Turtlenecks",
  "Women > Sweaters > V-Necks",
  "Women > Sweaters > Other",
  "Women > Swim > One Pieces",
  "Women > Swim > Bikinis",
  "Women > Swim > Coverups",
  "Women > Swim > Other",
  "Women > Skirts > A-Line",
  "Women > Skirts > Asymmetrical",
  "Women > Skirts > Maxi",
  "Women > Skirts > Midi",
  "Women > Skirts > Mini",
  "Women > Skirts > Pencil",
  "Women > Skirts > Pleated",
  "Women > Skirts > Other",
  "Women > Dresses > Asymmetrical",
  "Women > Dresses > Backless",
  "Women > Dresses > High Low",
  "Women > Dresses > Maxi",
  "Women > Dresses > Midi",
  "Women > Dresses > Mini",
  "Women > Dresses > Prom",
  "Women > Dresses > Strapless",
  "Women > Dresses > Wedding",
  "Women > Dresses > Other",
  "Women > Jumpsuits & Rompers > Jumpsuits",
  "Women > Jumpsuits & Rompers > Rompers",
  "Women > Jumpsuits & Rompers > Other",
  "Women > Accessories > Belts",
  "Women > Accessories > Hair Accessories",
  "Women > Accessories > Hats",
  "Women > Accessories > Scarves & Wraps",
  "Women > Accessories > Sunglasses",
  "Women > Accessories > Watches",
  "Women > Accessories > Other",
  "Women > Bags > Backpacks",
  "Women > Bags > Clutches",
  "Women > Bags > Cosmetic Bags",
  "Women > Bags > Hobo Bags",
  "Women > Bags > Messenger Bags",
  "Women > Bags > Satchels",
  "Women > Bags > Shoulder Bags",
  "Women > Bags > Totes",
  "Women > Bags > Other",
  "Women > Intimates & Sleepwear > Bras",
  "Women > Intimates & Sleepwear > Panties",
  "Women > Intimates & Sleepwear > Pajamas",
  "Women > Intimates & Sleepwear > Robes",
  "Women > Intimates & Sleepwear > Other",
  "Women > Suits & Blazers > Pant Suits",
  "Women > Suits & Blazers > Skirt Suits",
  "Women > Suits & Blazers > Blazers",
  "Women > Suits & Blazers > Other",

  // --- Men ---
  "Men > Shirts > Casual Button Down Shirts",
  "Men > Shirts > Dress Shirts",
  "Men > Shirts > Jerseys",
  "Men > Shirts > Polos",
  "Men > Shirts > Sweatshirts & Hoodies",
  "Men > Shirts > Tank Tops",
  "Men > Shirts > Tees - Long Sleeve",
  "Men > Shirts > Tees - Short Sleeve",
  "Men > Shirts > Other",
  "Men > Jackets & Coats > Blazers",
  "Men > Jackets & Coats > Jean Jackets",
  "Men > Jackets & Coats > Leather Jackets",
  "Men > Jackets & Coats > Puffer Jackets",
  "Men > Jackets & Coats > Raincoats",
  "Men > Jackets & Coats > Trench Coats",
  "Men > Jackets & Coats > Vests",
  "Men > Jackets & Coats > Windbreakers",
  "Men > Jackets & Coats > Other",
  "Men > Jeans > Boot Cut",
  "Men > Jeans > Relaxed",
  "Men > Jeans > Slim",
  "Men > Jeans > Straight Leg",
  "Men > Jeans > Other",
  "Men > Pants > Cargo",
  "Men > Pants > Chinos & Khakis",
  "Men > Pants > Dress Pants",
  "Men > Pants > Sweatpants & Joggers",
  "Men > Pants > Other",
  "Men > Shoes > Athletic Shoes",
  "Men > Shoes > Boots",
  "Men > Shoes > Dress Shoes",
  "Men > Shoes > Loafers & Slip-Ons",
  "Men > Shoes > Sandals",
  "Men > Shoes > Sneakers",
  "Men > Shoes > Other",
  "Men > Shorts > Cargo Shorts",
  "Men > Shorts > Casual Shorts",
  "Men > Shorts > Athletic Shorts",
  "Men > Shorts > Other",
  "Men > Sweaters > Cardigans",
  "Men > Sweaters > Crewnecks",
  "Men > Sweaters > Turtlenecks",
  "Men > Sweaters > V-Necks",
  "Men > Sweaters > Other",
  "Men > Swim > Board Shorts",
  "Men > Swim > Swim Trunks",
  "Men > Swim > Other",
  "Men > Suits & Blazers > Tuxedos",
  "Men > Suits & Blazers > Suits",
  "Men > Suits & Blazers > Blazers",
  "Men > Suits & Blazers > Other",
  "Men > Accessories > Belts",
  "Men > Accessories > Hats",
  "Men > Accessories > Ties",
  "Men > Accessories > Wallets",
  "Men > Accessories > Sunglasses",
  "Men > Accessories > Watches",
  "Men > Accessories > Other",
  "Men > Bags > Backpacks",
  "Men > Bags > Duffel Bags",
  "Men > Bags > Messenger Bags",
  "Men > Bags > Briefcases",
  "Men > Bags > Other",
  "Men > Underwear & Socks > Briefs & Boxers",
  "Men > Underwear & Socks > Socks",
  "Men > Underwear & Socks > Other",
  "Men > Grooming > Shaving & Hair Removal",
  "Men > Grooming > Cologne & Fragrance",
  "Men > Grooming > Other",

  // --- Beauty ---
  "Beauty > Makeup > Eyes",
  "Beauty > Makeup > Face",
  "Beauty > Makeup > Lips",
  "Beauty > Makeup > Tools",
  "Beauty > Skincare > Face",
  "Beauty > Skincare > Body",
  "Beauty > Skincare > Tools",
  "Beauty > Hair > Hair Care",
  "Beauty > Hair > Styling Products",
  "Beauty > Hair > Tools",
  "Beauty > Bath & Body > Body Wash & Shower Gel",
  "Beauty > Bath & Body > Lotion & Moisturizer",
  "Beauty > Bath & Body > Deodorants",
  "Beauty > Bath & Body > Other",
  "Beauty > Tools > Makeup Brushes",
  "Beauty > Tools > Press-On Nails",
  "Beauty > Tools > Other",

  // --- Home ---
  "Home > Bath > Towels",
  "Home > Bath > Bath Rugs",
  "Home > Bath > Other",
  "Home > Bedding > Sheets",
  "Home > Bedding > Comforters & Duvets",
  "Home > Bedding > Pillows",
  "Home > Bedding > Other",
  "Home > Dining & Entertaining > Dinnerware",
  "Home > Dining & Entertaining > Glassware",
  "Home > Dining & Entertaining > Table Linens",
  "Home > Dining & Entertaining > Other",
  "Home > Home Accents > Candles & Holders",
  "Home > Home Accents > Decorative Pillows",
  "Home > Home Accents > Mirrors",
  "Home > Home Accents > Other",
  "Home > Kitchen > Cookware",
  "Home > Kitchen > Bakeware",
  "Home > Kitchen > Small Appliances",
  "Home > Kitchen > Kitchen Utensils",
  "Home > Kitchen > Other",
  "Home > Office > Desk Organizers",
  "Home > Office > Writing Instruments",
  "Home > Office > Other",
  "Home > Organization > Storage Bins",
  "Home > Organization > Closet Organizers",
  "Home > Organization > Other",
  "Home > Wall Art > Prints",
  "Home > Wall Art > Paintings",
  "Home > Wall Art > Other",

  // --- Kids ---
  "Kids > Accessories > Hats",
  "Kids > Accessories > Sunglasses",
  "Kids > Accessories > Other",
  "Kids > Bags > Backpacks",
  "Kids > Bags > Lunch Bags",
  "Kids > Bags > Other",
  "Kids > Boys Clothing > Tops",
  "Kids > Boys Clothing > Bottoms",
  "Kids > Boys Clothing > Outerwear",
  "Kids > Boys Clothing > Other",
  "Kids > Boys Shoes > Athletic",
  "Kids > Boys Shoes > Boots",
  "Kids > Boys Shoes > Sneakers",
  "Kids > Boys Shoes > Other",
  "Kids > Girls Clothing > Tops",
  "Kids > Girls Clothing > Bottoms",
  "Kids > Girls Clothing > Dresses",
  "Kids > Girls Clothing > Outerwear",
  "Kids > Girls Clothing > Other",
  "Kids > Girls Shoes > Athletic",
  "Kids > Girls Shoes > Boots",
  "Kids > Girls Shoes > Flats",
  "Kids > Girls Shoes > Other",
  "Kids > Toys > Dolls",
  "Kids > Toys > Action Figures",
  "Kids > Toys > Games & Puzzles",
  "Kids > Toys > Stuffed Animals",
  "Kids > Toys > Other",

  // --- Pets ---
  "Pets > Pet Apparel > Dog Sweaters",
  "Pets > Pet Apparel > Cat Costumes",
  "Pets > Pet Apparel > Other",
  "Pets > Pet Collars & Leashes > Collars",
  "Pets > Pet Collars & Leashes > Leashes",
  "Pets > Pet Collars & Leashes > Harnesses",
  "Pets > Pet Collars & Leashes > Other",
  "Pets > Pet Grooming > Shampoos",
  "Pets > Pet Grooming > Brushes",
  "Pets > Pet Grooming > Other",
  "Pets > Pet Toys > Dog Toys",
  "Pets > Pet Toys > Cat Toys",
  "Pets > Pet Toys > Other",

  // --- Electronics ---
  "Electronics > Cameras > DSLR",
  "Electronics > Cameras > Lenses",
  "Electronics > Cameras > Other",
  "Electronics > Computers & Laptops > Laptops",
  "Electronics > Computers & Laptops > Tablets",
  "Electronics > Computers & Laptops > Other",
  "Electronics > Phones & Accessories > Phone Cases",
  "Electronics > Phones & Accessories > Chargers",
  "Electronics > Phones & Accessories > Other",
  "Electronics > Smart Home & Home Security > Cameras",
  "Electronics > Smart Home & Home Security > Other",
  "Electronics > Video Games & Consoles > Consoles",
  "Electronics > Video Games & Consoles > Games",
  "Electronics > Video Games & Consoles > Accessories",
  "Electronics > Video Games & Consoles > Other",
  "Electronics > Wearable Technology > Smartwatches",
  "Electronics > Wearable Technology > Fitness Trackers",
  "Electronics > Wearable Technology > Other"
];

module.exports = { POSHMARK_TAXONOMY };
