const VINTED_TAXONOMY = [
  // --- Women ---
  "Women > Clothes > Tops & T-shirts > T-shirts",
  "Women > Clothes > Tops & T-shirts > Blouses",
  "Women > Clothes > Tops & T-shirts > Tunics",
  "Women > Clothes > Tops & T-shirts > Camisoles",
  "Women > Clothes > Tops & T-shirts > Sweatshirts & Hoodies",
  "Women > Clothes > Tops & T-shirts > Other",
  "Women > Clothes > Dresses > Maxi Dresses",
  "Women > Clothes > Dresses > Midi Dresses",
  "Women > Clothes > Dresses > Mini Dresses",
  "Women > Clothes > Dresses > Other",
  "Women > Clothes > Coats & Jackets > Blazers",
  "Women > Clothes > Coats & Jackets > Denim Jackets",
  "Women > Clothes > Coats & Jackets > Puffer Jackets",
  "Women > Clothes > Coats & Jackets > Other",
  "Women > Clothes > Pants & Leggings > Leggings",
  "Women > Clothes > Pants & Leggings > Wide Leg Pants",
  "Women > Clothes > Pants & Leggings > Other",
  "Women > Clothes > Skirts > Maxi Skirts",
  "Women > Clothes > Skirts > Mini Skirts",
  "Women > Clothes > Skirts > Other",
  "Women > Clothes > Swimwear > Bikinis",
  "Women > Clothes > Swimwear > One-pieces",
  "Women > Clothes > Swimwear > Other",
  "Women > Clothes > Activewear > Tops",
  "Women > Clothes > Activewear > Bottoms",
  "Women > Clothes > Activewear > Other",
  "Women > Clothes > Underwear & Nightwear > Bras",
  "Women > Clothes > Underwear & Nightwear > Panties",
  "Women > Clothes > Underwear & Nightwear > Other",
  "Women > Shoes > Heels > Pumps",
  "Women > Shoes > Heels > Sandals",
  "Women > Shoes > Flats",
  "Women > Shoes > Boots",
  "Women > Shoes > Sneakers",
  "Women > Shoes > Sandals",
  "Women > Shoes > Other",
  "Women > Bags > Backpacks",
  "Women > Bags > Handbags",
  "Women > Bags > Clutches",
  "Women > Bags > Totes",
  "Women > Bags > Other",
  "Women > Accessories > Belts",
  "Women > Accessories > Hats & Caps",
  "Women > Accessories > Sunglasses",
  "Women > Accessories > Watches",
  "Women > Accessories > Other",
  "Women > Beauty > Makeup > Face",
  "Women > Beauty > Makeup > Eyes",
  "Women > Beauty > Makeup > Lips",
  "Women > Beauty > Skincare",
  "Women > Beauty > Hair Care",
  "Women > Beauty > Fragrances",

  // --- Men ---
  "Men > Clothes > Tops & T-shirts > T-shirts",
  "Men > Clothes > Tops & T-shirts > Shirts",
  "Men > Clothes > Tops & T-shirts > Polos",
  "Men > Clothes > Tops & T-shirts > Sweatshirts & Hoodies",
  "Men > Clothes > Tops & T-shirts > Other",
  "Men > Clothes > Coats & Jackets > Blazers",
  "Men > Clothes > Coats & Jackets > Denim Jackets",
  "Men > Clothes > Coats & Jackets > Puffer Jackets",
  "Men > Clothes > Coats & Jackets > Other",
  "Men > Clothes > Pants & Jeans > Jeans",
  "Men > Clothes > Pants & Jeans > Chinos",
  "Men > Clothes > Pants & Jeans > Other",
  "Men > Clothes > Shorts",
  "Men > Clothes > Activewear",
  "Men > Clothes > Swimwear",
  "Men > Clothes > Underwear",
  "Men > Shoes > Sneakers",
  "Men > Shoes > Boots",
  "Men > Shoes > Dress Shoes",
  "Men > Shoes > Sandals & Slides",
  "Men > Shoes > Loafers & Slip-ons",
  "Men > Shoes > Other",
  "Men > Accessories > Hats",
  "Men > Accessories > Belts",
  "Men > Accessories > Ties",
  "Men > Accessories > Sunglasses",
  "Men > Accessories > Watches",
  "Men > Accessories > Bags",
  "Men > Accessories > Other",

  // --- Kids ---
  "Kids > Clothing > Girls Clothing > Tops",
  "Kids > Clothing > Girls Clothing > Bottoms",
  "Kids > Clothing > Girls Clothing > Dresses",
  "Kids > Clothing > Girls Clothing > Other",
  "Kids > Clothing > Boys Clothing > Tops",
  "Kids > Clothing > Boys Clothing > Bottoms",
  "Kids > Clothing > Boys Clothing > Other",
  "Kids > Shoes > Girls Shoes",
  "Kids > Shoes > Boys Shoes",
  "Kids > Toys > Dolls",
  "Kids > Toys > Board Games",
  "Kids > Toys > Action Figures",
  "Kids > Toys > Other",

  // --- Home ---
  "Home > Home Decor > Candles",
  "Home > Home Decor > Frames & Pictures",
  "Home > Home Decor > Other",
  "Home > Home Textiles > Bedding",
  "Home > Home Textiles > Towels",
  "Home > Home Textiles > Other",
  "Home > Tableware & Kitchen > Cookware",
  "Home > Tableware & Kitchen > Other",
  "Home > Storage & Organization > Storage Bins",
  "Home > Storage & Organization > Other",

  // --- Entertainment ---
  "Entertainment > Video Games > Consoles",
  "Entertainment > Video Games > Games",
  "Entertainment > Video Games > Accessories",
  "Entertainment > Books > Fiction",
  "Entertainment > Books > Non-fiction",
  "Entertainment > Music > Vinyl & CDs"
];

module.exports = { VINTED_TAXONOMY };
